<?php
// Copyright (C) 2010-2014 Combodo SARL
//
//   This file is part of iTop.
//
//   iTop is free software; you can redistribute it and/or modify	
//   it under the terms of the GNU Affero General Public License as published by
//   the Free Software Foundation, either version 3 of the License, or
//   (at your option) any later version.
//
//   iTop is distributed in the hope that it will be useful,
//   but WITHOUT ANY WARRANTY; without even the implied warranty of
//   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//   GNU Affero General Public License for more details.
//
//   You should have received a copy of the GNU Affero General Public License
//   along with iTop. If not, see <http://www.gnu.org/licenses/>


/**
 * Localized data
 *
 * @copyright   Copyright (C) 2010-2012 Combodo SARL
 * @license     http://opensource.org/licenses/AGPL-3.0
 */

Dict::Add('NL NL', 'Dutch', 'Nederlands', array(
	'Menu:CouncilRequestManagement' => 'Gemeenteraad',
	'Menu:CouncilRequestManagement+' => 'Gemeenteraad',
	'Menu:CouncilRequestManagementProvider' => 'Helpdesk leverancier',
	'Menu:CouncilRequestManagementProvider+' => 'Helpdesk leverancier',
	'Menu:CouncilRequest:Provider' => 'Open tickets overgebracht naar leverancier',
	'Menu:CouncilRequest:Provider+' => 'Open tickets overgebracht naar leverancier',
	'Menu:CouncilRequest:Overview' => 'Overzicht',
	'Menu:CouncilRequest:Overview+' => 'Gemeenteraad overzicht',
	'Menu:NewCouncilRequest' => 'Nieuwe vraag',
	'Menu:NewCouncilRequest+' => 'Maak een nieuwe vraag aan',
	'Menu:SearchCouncilRequests' => 'Zoek naar vragen',
	'Menu:SearchCouncilRequests+' => '',
	'Menu:CouncilRequest:Shortcuts' => 'Snelkoppelingen',
	'Menu:CouncilRequest:Shortcuts+' => '',
	'Menu:CouncilRequest:MyRequests' => 'Vragen toegewezen aan mij',
	'Menu:CouncilRequest:MyRequests+' => 'Vragen toegewezen aan mij (als behandelaar of schepen)',
	'Menu:CouncilRequest:MySupportRequests' => 'Vragen van mij',
	'Menu:CouncilRequest:MySupportRequests+' => 'Vragen van mij',
	'Menu:CouncilRequest:EscalatedRequests' => 'Dringende vragen',
	'Menu:CouncilRequest:EscalatedRequests+' => 'Dringende vragen',
	'Menu:CouncilRequest:OpenRequests' => 'Alle openstaande vragen',
	'Menu:CouncilRequest:OpenRequests+' => 'Alle openstaande vragen',
	'UI:WelcomeMenu:MyAssignedCalls' => 'Vragen toegewezen aan mij',
	'UI-RequestManagementOverview-RequestByType-last-14-days' => 'Vragen van de afgelopen 14 dagen (per type)',
	'UI-RequestManagementOverview-Last-14-days' => 'Vragen van de afgelopen 14 dagen (per dag)',
	'UI-RequestManagementOverview-OpenRequestByStatus' => 'Open vragen per status',
	'UI-RequestManagementOverview-OpenRequestByAgent' => 'Open vragen per medewerker',
	'UI-RequestManagementOverview-OpenRequestByType' => 'Open vragen per type',
	'UI-RequestManagementOverview-OpenRequestByCustomer' => 'Open vragen per organisatie',
	'Class:CouncilRequest:KnownErrorList' => 'Bekende fouten',
));

// Dictionnary conventions
// Class:<class_name>
// Class:<class_name>+
// Class:<class_name>/Attribute:<attribute_code>
// Class:<class_name>/Attribute:<attribute_code>+
// Class:<class_name>/Attribute:<attribute_code>/Value:<value>
// Class:<class_name>/Attribute:<attribute_code>/Value:<value>+
// Class:<class_name>/Stimulus:<stimulus_code>
// Class:<class_name>/Stimulus:<stimulus_code>+

//
// Class: CouncilRequest
//

Dict::Add('NL NL', 'Dutch', 'Nederlands', array(
	'Class:CouncilRequest' => 'Gebruikerstickets',
	'Class:CouncilRequest+' => '',
	'Class:CouncilRequest/Attribute:status' => 'Status',
	'Class:CouncilRequest/Attribute:status+' => '',
	'Class:CouncilRequest/Attribute:status/Value:new' => 'Nieuw',
	'Class:CouncilRequest/Attribute:status/Value:new+' => '',
	'Class:CouncilRequest/Attribute:status/Value:escalated_tto' => 'Geëscalleerd TTO',
	'Class:CouncilRequest/Attribute:status/Value:escalated_tto+' => '',
	'Class:CouncilRequest/Attribute:status/Value:assigned' => 'Toegewezen',
	'Class:CouncilRequest/Attribute:status/Value:assigned+' => '',
	'Class:CouncilRequest/Attribute:status/Value:escalated_ttr' => 'Geëscaleerd TTR',
	'Class:CouncilRequest/Attribute:status/Value:escalated_ttr+' => '',
	'Class:CouncilRequest/Attribute:status/Value:waiting_for_approval' => 'Wacht op goedkeuring',
	'Class:CouncilRequest/Attribute:status/Value:waiting_for_approval+' => '',
	'Class:CouncilRequest/Attribute:status/Value:approved' => 'Goedgekeurd',
	'Class:CouncilRequest/Attribute:status/Value:approved+' => '',
	'Class:CouncilRequest/Attribute:status/Value:rejected' => 'Afgewezen',
	'Class:CouncilRequest/Attribute:status/Value:rejected+' => '',
	'Class:CouncilRequest/Attribute:status/Value:pending' => 'Wachtend',
	'Class:CouncilRequest/Attribute:status/Value:pending+' => '',
	'Class:CouncilRequest/Attribute:status/Value:resolved' => 'Opgelost',
	'Class:CouncilRequest/Attribute:status/Value:resolved+' => '',
	'Class:CouncilRequest/Attribute:status/Value:closed' => 'Gesloten',
	'Class:CouncilRequest/Attribute:status/Value:closed+' => '',
	'Class:CouncilRequest/Attribute:request_type' => 'Type verzoek',
	'Class:CouncilRequest/Attribute:request_type+' => '',
	'Class:CouncilRequest/Attribute:request_type/Value:service_request' => 'Vraag om hulp',
	'Class:CouncilRequest/Attribute:request_type/Value:service_request+' => 'Service request',
	'Class:CouncilRequest/Attribute:publishstate' => 'Status publicatie',
	'Class:CouncilRequest/Attribute:publishstate+' => '',
	'Class:CouncilRequest/Attribute:publishstate/Value:1' => 'Niet gepubliceerd',
	'Class:CouncilRequest/Attribute:publishstate/Value:1+' => '',
	'Class:CouncilRequest/Attribute:publishstate/Value:2' => 'Gepubliceerd',
	'Class:CouncilRequest/Attribute:publishstate/Value:2+' => '',
	'Class:CouncilRequest/Attribute:publishstate/Value:3' => 'Publicatie verworpen',
	'Class:CouncilRequest/Attribute:publishstate/Value:3+' => '',
	'Class:CouncilRequest/Attribute:publishstate/Value:4' => 'GR-lid geïnformeerd, nog niet gepubliceerd',
	'Class:CouncilRequest/Attribute:publishstate/Value:4+' => '',	
	'Class:CouncilRequest/Attribute:priority' => 'Prioriteit',
	'Class:CouncilRequest/Attribute:priority+' => '',
	'Class:CouncilRequest/Attribute:priority/Value:1' => 'kritiek',
	'Class:CouncilRequest/Attribute:priority/Value:1+' => 'kritisch',
	'Class:CouncilRequest/Attribute:priority/Value:2' => 'hoog',
	'Class:CouncilRequest/Attribute:priority/Value:2+' => 'hoog',
	'Class:CouncilRequest/Attribute:priority/Value:3' => 'gemiddeld',
	'Class:CouncilRequest/Attribute:priority/Value:3+' => 'normaal',
	'Class:CouncilRequest/Attribute:priority/Value:4' => 'laag',
	'Class:CouncilRequest/Attribute:priority/Value:4+' => 'laag',
	'Class:CouncilRequest/Attribute:urgency' => 'Urgentie',
	'Class:CouncilRequest/Attribute:urgency+' => '',
	'Class:CouncilRequest/Attribute:urgency/Value:1' => 'kritiek',
	'Class:CouncilRequest/Attribute:urgency/Value:1+' => 'kritisch',
	'Class:CouncilRequest/Attribute:urgency/Value:2' => 'hoog',
	'Class:CouncilRequest/Attribute:urgency/Value:2+' => 'hoog',
	'Class:CouncilRequest/Attribute:urgency/Value:3' => 'gemiddeld',
	'Class:CouncilRequest/Attribute:urgency/Value:3+' => 'normaal',
	'Class:CouncilRequest/Attribute:urgency/Value:4' => 'laag',
	'Class:CouncilRequest/Attribute:urgency/Value:4+' => 'laag',
	'Class:CouncilRequest/Attribute:origin' => 'Oorsprong',
	'Class:CouncilRequest/Attribute:origin+' => '',
	'Class:CouncilRequest/Attribute:origin/Value:mail' => 'mail',
	'Class:CouncilRequest/Attribute:origin/Value:mail+' => 'mail',
	'Class:CouncilRequest/Attribute:origin/Value:monitoring' => 'monitoring',
	'Class:CouncilRequest/Attribute:origin/Value:monitoring+' => 'monitoring',
	'Class:CouncilRequest/Attribute:origin/Value:phone' => 'telefoon',
	'Class:CouncilRequest/Attribute:origin/Value:phone+' => 'telefoon',
	'Class:CouncilRequest/Attribute:origin/Value:portal' => 'portaal',
	'Class:CouncilRequest/Attribute:origin/Value:portal+' => 'portaal',
	'Class:CouncilRequest/Attribute:origin/Value:in_person' => 'in persoon',
    'Class:CouncilRequest/Attribute:origin/Value:in_person+' => 'in persoon',
	'Class:CouncilRequest/Attribute:approver_id' => 'Goedkeurder',
	'Class:CouncilRequest/Attribute:approver_id+' => '',
	'Class:CouncilRequest/Attribute:approver_email' => 'Goedkeurder Email',
	'Class:CouncilRequest/Attribute:approver_email+' => '',
	'Class:CouncilRequest/Attribute:service_id' => 'Dienst',
	'Class:CouncilRequest/Attribute:service_id+' => '',
	'Class:CouncilRequest/Attribute:service_name' => 'Dienst naam',
	'Class:CouncilRequest/Attribute:service_name+' => '',
	'Class:CouncilRequest/Attribute:servicesubcategory_id' => 'Dienst subcategorie',
	'Class:CouncilRequest/Attribute:servicesubcategory_id+' => '',
	'Class:CouncilRequest/Attribute:servicesubcategory_name' => 'Dienst subcategorie naam',
	'Class:CouncilRequest/Attribute:servicesubcategory_name+' => '',
	'Class:CouncilRequest/Attribute:escalation_flag' => 'Hot Flag',
	'Class:CouncilRequest/Attribute:escalation_flag+' => '',
	'Class:CouncilRequest/Attribute:escalation_flag/Value:no' => 'Nee',
	'Class:CouncilRequest/Attribute:escalation_flag/Value:no+' => 'Nee',
	'Class:CouncilRequest/Attribute:escalation_flag/Value:yes' => 'Ja',
	'Class:CouncilRequest/Attribute:escalation_flag/Value:yes+' => 'Ja',
	'Class:CouncilRequest/Attribute:escalation_reason' => 'Hot reason',
	'Class:CouncilRequest/Attribute:escalation_reason+' => '',
	'Class:CouncilRequest/Attribute:assignment_date' => 'Datum toegewezen',
	'Class:CouncilRequest/Attribute:assignment_date+' => '',
	'Class:CouncilRequest/Attribute:resolution_date' => 'Datum opgelost',
	'Class:CouncilRequest/Attribute:resolution_date+' => '',
	'Class:CouncilRequest/Attribute:last_pending_date' => 'Laatste wachtend datum',
	'Class:CouncilRequest/Attribute:last_pending_date+' => '',
	'Class:CouncilRequest/Attribute:cumulatedpending' => 'samengeteld wachtend',
	'Class:CouncilRequest/Attribute:cumulatedpending+' => '',
	'Class:CouncilRequest/Attribute:tto' => 'TTO',
	'Class:CouncilRequest/Attribute:tto+' => '',
	'Class:CouncilRequest/Attribute:ttr' => 'TTR',
	'Class:CouncilRequest/Attribute:ttr+' => '',
	'Class:CouncilRequest/Attribute:tto_escalation_deadline' => 'TTO Deadline',
	'Class:CouncilRequest/Attribute:tto_escalation_deadline+' => '',
	'Class:CouncilRequest/Attribute:sla_tto_passed' => 'SLA tto passed',
	'Class:CouncilRequest/Attribute:sla_tto_passed+' => '',
	'Class:CouncilRequest/Attribute:sla_tto_over' => 'SLA tto over',
	'Class:CouncilRequest/Attribute:sla_tto_over+' => '',
	'Class:CouncilRequest/Attribute:ttr_escalation_deadline' => 'TTR Deadline',
	'Class:CouncilRequest/Attribute:ttr_escalation_deadline+' => '',
	'Class:CouncilRequest/Attribute:sla_ttr_passed' => 'SLA ttr gepasseerd',
	'Class:CouncilRequest/Attribute:sla_ttr_passed+' => '',
	'Class:CouncilRequest/Attribute:sla_ttr_over' => 'SLA ttr over',
	'Class:CouncilRequest/Attribute:sla_ttr_over+' => '',
	'Class:CouncilRequest/Attribute:time_spent' => 'Resolutie vertraging',
	'Class:CouncilRequest/Attribute:time_spent+' => '',
	'Class:CouncilRequest/Attribute:resolution_code' => 'Resolutie code',
	'Class:CouncilRequest/Attribute:resolution_code+' => '',
	'Class:CouncilRequest/Attribute:resolution_code/Value:assistance' => 'assistentie',
	'Class:CouncilRequest/Attribute:resolution_code/Value:assistance+' => 'assistentie',
	'Class:CouncilRequest/Attribute:resolution_code/Value:bug fixed' => 'bug opgelost',
	'Class:CouncilRequest/Attribute:resolution_code/Value:bug fixed+' => 'bug ogelost',
	'Class:CouncilRequest/Attribute:resolution_code/Value:hardware repair' => 'hardware gerepareerd',
	'Class:CouncilRequest/Attribute:resolution_code/Value:hardware repair+' => 'hardware gerepareerd',
	'Class:CouncilRequest/Attribute:resolution_code/Value:other' => 'andere',
	'Class:CouncilRequest/Attribute:resolution_code/Value:other+' => 'andere',
	'Class:CouncilRequest/Attribute:resolution_code/Value:software patch' => 'software patch',
	'Class:CouncilRequest/Attribute:resolution_code/Value:software patch+' => 'software patch',
	'Class:CouncilRequest/Attribute:resolution_code/Value:system update' => 'systeem update',
	'Class:CouncilRequest/Attribute:resolution_code/Value:system update+' => 'systeem update',
	'Class:CouncilRequest/Attribute:resolution_code/Value:training' => 'training',
	'Class:CouncilRequest/Attribute:resolution_code/Value:training+' => 'training',
	'Class:CouncilRequest/Attribute:solution' => 'Oplossing',
	'Class:CouncilRequest/Attribute:solution+' => '',
	'Class:CouncilRequest/Attribute:pending_reason' => 'Reden waarom het in afwachting staat',
	'Class:CouncilRequest/Attribute:pending_reason+' => '',
	'Class:CouncilRequest/Attribute:parent_request_id' => 'Hoofdticket',
	'Class:CouncilRequest/Attribute:parent_request_id+' => '',
	'Class:CouncilRequest/Attribute:parent_incident_id' => 'Hoofdincident',
	'Class:CouncilRequest/Attribute:parent_incident_id+' => '',
	'Class:CouncilRequest/Attribute:parent_request_ref' => 'Ref request',
	'Class:CouncilRequest/Attribute:parent_request_ref+' => '',
	'Class:CouncilRequest/Attribute:parent_problem_id' => 'Hoofdprobleem',
	'Class:CouncilRequest/Attribute:parent_problem_id+' => '',
	'Class:CouncilRequest/Attribute:parent_problem_ref' => 'Ref probleem',
	'Class:CouncilRequest/Attribute:parent_problem_ref+' => '',
	'Class:CouncilRequest/Attribute:parent_change_id' => 'Hoofdchange',
	'Class:CouncilRequest/Attribute:parent_change_id+' => '',
	'Class:CouncilRequest/Attribute:parent_change_ref' => 'Ref change',
	'Class:CouncilRequest/Attribute:parent_change_ref+' => '',
	'Class:CouncilRequest/Attribute:related_request_list' => 'Sub Tickets',
	'Class:CouncilRequest/Attribute:related_request_list+' => 'Alle tickets die gelinkt zijn aan dit hoofdticket',
	'Class:CouncilRequest/Attribute:public_log' => 'Publiek commentaar',
	'Class:CouncilRequest/Attribute:public_log+' => '',
	'Class:CouncilRequest/Attribute:private_log' => 'Privé commentaar',
	'Class:CouncilRequest/Attribute:private_log+' => '',
	'Class:CouncilRequest/Attribute:publish_log' => 'Tekst om te publiceren',
	'Class:CouncilRequest/Attribute:publish_log+' => '',
	'Class:CouncilRequest/Attribute:user_satisfaction' => 'Gebruikerstevredenheid',
	'Class:CouncilRequest/Attribute:user_satisfaction+' => '',
	'Class:CouncilRequest/Attribute:user_satisfaction/Value:1' => 'Zeer tevreden',
	'Class:CouncilRequest/Attribute:user_satisfaction/Value:1+' => 'Zeer tevreden',
	'Class:CouncilRequest/Attribute:user_satisfaction/Value:2' => 'Tamelijk tevreden',
	'Class:CouncilRequest/Attribute:user_satisfaction/Value:2+' => 'Takelijk tevreden',
	'Class:CouncilRequest/Attribute:user_satisfaction/Value:3' => 'Tamelijk ontevreden',
	'Class:CouncilRequest/Attribute:user_satisfaction/Value:3+' => 'Tamelijk ontevreden',
	'Class:CouncilRequest/Attribute:user_satisfaction/Value:4' => 'Zeer ontevreden',
	'Class:CouncilRequest/Attribute:user_satisfaction/Value:4+' => 'Zeer ontevreden',
	'Class:CouncilRequest/Attribute:parent_request_id_friendlyname' => 'parent_request_id_friendlyname',
	'Class:CouncilRequest/Attribute:parent_request_id_friendlyname+' => '',
	'Class:CouncilRequest/Stimulus:ev_assign' => 'Wijs toe',
	'Class:CouncilRequest/Stimulus:ev_assign+' => '',
	'Class:CouncilRequest/Stimulus:ev_reassign' => 'Wijs opnieuw toe',
	'Class:CouncilRequest/Stimulus:ev_reassign+' => '',
	'Class:CouncilRequest/Stimulus:ev_approve' => 'Keur goed',
	'Class:CouncilRequest/Stimulus:ev_approve+' => '',
	'Class:CouncilRequest/Stimulus:ev_reject' => 'Keur af',
	'Class:CouncilRequest/Stimulus:ev_reject+' => '',
	'Class:CouncilRequest/Stimulus:ev_pending' => 'In afwachting',
	'Class:CouncilRequest/Stimulus:ev_pending+' => '',
	'Class:CouncilRequest/Stimulus:ev_timeout' => 'Timeout',
	'Class:CouncilRequest/Stimulus:ev_timeout+' => '',
	'Class:CouncilRequest/Stimulus:ev_autoresolve' => 'Automatisch oplossen',
	'Class:CouncilRequest/Stimulus:ev_autoresolve+' => '',
	'Class:CouncilRequest/Stimulus:ev_autoclose' => 'Automatisch sluiten',
	'Class:CouncilRequest/Stimulus:ev_autoclose+' => '',
	'Class:CouncilRequest/Stimulus:ev_resolve' => 'Markeren als opgelost',
	'Class:CouncilRequest/Stimulus:ev_resolve+' => '',
	'Class:CouncilRequest/Stimulus:ev_close' => 'Sluit dit verzoek',
	'Class:CouncilRequest/Stimulus:ev_close+' => '',
	'Class:CouncilRequest/Stimulus:ev_reopen' => 'Her-open',
	'Class:CouncilRequest/Stimulus:ev_reopen+' => '',
	'Class:CouncilRequest/Stimulus:ev_wait_for_approval' => 'Wacht op goedkeuring',
	'Class:CouncilRequest/Stimulus:ev_wait_for_approval+' => '',
	'Class:CouncilRequest/Error:CannotAssignParentRequestIdToSelf' => 'Kan niet toewijzen aan hoofdverzoek en aan het verzoek zelf',
	'Class:CouncilRequest/Attribute:reminder' => 'Herinnering',
	'Class:CouncilRequest/Attribute:reminder+' => '',	
	'Class:CouncilRequest/Attribute:councildate' => 'Datum gemeenteraad',
	'Class:CouncilRequest/Attribute:councildate+' => '',	
	'Class:CouncilRequest/Attribute:council_member_id' => 'Verantwoordelijke schepen',	
	'Class:CouncilRequest/Attribute:council_member_id+' => '',	
	

	'Class:CouncilRequest/Method:ResolveChildTickets' => 'ResolveChildTickets',
	'Class:CouncilRequest/Method:ResolveChildTickets+' => 'Cascade the resolution to child requests (ev_autoresolve), and align the following characteristics of the request: service, team, agent, resolution info',
));
