<?php
// Copyright (C) 2010-2014 Combodo SARL
//
//   This file is part of iTop.
//
//   iTop is free software; you can redistribute it and/or modify	
//   it under the terms of the GNU Affero General Public License as published by
//   the Free Software Foundation, either version 3 of the License, or
//   (at your option) any later version.
//
//   iTop is distributed in the hope that it will be useful,
//   but WITHOUT ANY WARRANTY; without even the implied warranty of
//   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//   GNU Affero General Public License for more details.
//
//   You should have received a copy of the GNU Affero General Public License
//   along with iTop. If not, see <http://www.gnu.org/licenses/>


/**
 * Localized data
 *
 * @copyright   Copyright (C) 2010-2012 Combodo SARL
 * @license     http://opensource.org/licenses/AGPL-3.0
 */

Dict::Add('NL NL', 'Dutch', 'Nederlands', array(
	'Menu:BuildingRequestManagement' => 'Omgeving',
	'Menu:BuildingRequestManagement+' => 'Omgeving',
	'Menu:BuildingRequestManagementProvider' => 'Helpdesk leverancier',
	'Menu:BuildingRequestManagementProvider+' => 'Helpdesk leverancier',
	'Menu:BuildingRequest:Provider' => 'Open tickets overgebracht naar leverancier',
	'Menu:BuildingRequest:Provider+' => 'Open tickets overgebracht naar leverancier',
	'Menu:BuildingRequest:Overview' => 'Overzicht',
	'Menu:BuildingRequest:Overview+' => 'Omgeving overzicht',
	'Menu:NewBuildingRequest' => 'Nieuw ticket',
	'Menu:NewBuildingRequest+' => 'Maak een nieuw ticket aan',
	'Menu:SearchBuildingRequests' => 'Zoek naar tickets',
	'Menu:SearchBuildingRequests+' => 'Zoek naar tickets',
	'Menu:BuildingRequest:Shortcuts' => 'Snelkoppelingen',
	'Menu:BuildingRequest:Shortcuts+' => '',
	'Menu:BuildingRequest:MyRequests' => 'Tickets toegewezen aan mij',
	'Menu:BuildingRequest:MyRequests+' => 'Tickets toegewezen aan mij (als behandelaar)',
	'Menu:BuildingRequest:MySupportRequests' => 'Tickets van mij',
	'Menu:BuildingRequest:MySupportRequests+' => 'Tickets van mij',
	'Menu:BuildingRequest:EscalatedRequests' => 'Dringende tickets',
	'Menu:BuildingRequest:EscalatedRequests+' => 'Dringende tickets',
	'Menu:BuildingRequest:OpenRequests' => 'Alle openstaande tickets',
	'Menu:BuildingRequest:OpenRequests+' => 'Alle openstaande tickets',
	'UI:WelcomeMenu:MyAssignedCalls' => 'Tickets toegewezen aan mij',
	'UI-RequestManagementOverview-RequestByType-last-14-days' => 'Tickets van de afgelopen 14 dagen (per type)',
	'UI-RequestManagementOverview-Last-14-days' => 'Tickets van de afgelopen 14 dagen (per dag)',
	'UI-RequestManagementOverview-OpenRequestByStatus' => 'Open tickets per status',
	'UI-RequestManagementOverview-OpenRequestByAgent' => 'Open tickets per medewerker',
	'UI-RequestManagementOverview-OpenRequestByType' => 'Open tickets per type',
	'UI-RequestManagementOverview-OpenRequestByCustomer' => 'Open tickets per organisatie',
	'Class:BuildingRequest:KnownErrorList' => 'Bekende fouten',
));

// Dictionnary conventions
// Class:<class_name>
// Class:<class_name>+
// Class:<class_name>/Attribute:<attribute_code>
// Class:<class_name>/Attribute:<attribute_code>+
// Class:<class_name>/Attribute:<attribute_code>/Value:<value>
// Class:<class_name>/Attribute:<attribute_code>/Value:<value>+
// Class:<class_name>/Stimulus:<stimulus_code>
// Class:<class_name>/Stimulus:<stimulus_code>+

//
// Class: BuildingRequest
//

Dict::Add('NL NL', 'Dutch', 'Nederlands', array(
	'Class:BuildingRequest' => 'Gebruikerstickets',
	'Class:BuildingRequest+' => '',
	'Class:BuildingRequest/Attribute:status' => 'Status',
	'Class:BuildingRequest/Attribute:status+' => '',
	'Class:BuildingRequest/Attribute:address_allotment' => 'Adres',
	'Class:BuildingRequest/Attribute:address_allotment+' => 'Adres van de verkaveling,...',
	'Class:BuildingRequest/Attribute:status/Value:new' => 'Nieuw',
	'Class:BuildingRequest/Attribute:status/Value:new+' => '',
	'Class:BuildingRequest/Attribute:status/Value:escalated_tto' => 'Geëscalleerd TTO',
	'Class:BuildingRequest/Attribute:status/Value:escalated_tto+' => '',
	'Class:BuildingRequest/Attribute:status/Value:assigned' => 'Toegewezen',
	'Class:BuildingRequest/Attribute:status/Value:assigned+' => '',
	'Class:BuildingRequest/Attribute:status/Value:escalated_ttr' => 'Geëscaleerd TTR',
	'Class:BuildingRequest/Attribute:status/Value:escalated_ttr+' => '',
	'Class:BuildingRequest/Attribute:status/Value:waiting_for_approval' => 'Wacht op goedkeuring',
	'Class:BuildingRequest/Attribute:status/Value:waiting_for_approval+' => '',
	'Class:BuildingRequest/Attribute:status/Value:approved' => 'Goedgekeurd',
	'Class:BuildingRequest/Attribute:status/Value:approved+' => '',
	'Class:BuildingRequest/Attribute:status/Value:rejected' => 'Afgewezen',
	'Class:BuildingRequest/Attribute:status/Value:rejected+' => '',
	'Class:BuildingRequest/Attribute:status/Value:pending' => 'Wachtend',
	'Class:BuildingRequest/Attribute:status/Value:pending+' => '',
	'Class:BuildingRequest/Attribute:status/Value:resolved' => 'Opgelost',
	'Class:BuildingRequest/Attribute:status/Value:resolved+' => '',
	'Class:BuildingRequest/Attribute:status/Value:closed' => 'Gesloten',
	'Class:BuildingRequest/Attribute:status/Value:closed+' => '',
	'Class:BuildingRequest/Attribute:request_type' => 'Type verzoek',
	'Class:BuildingRequest/Attribute:request_type+' => '',
	'Class:BuildingRequest/Attribute:request_type/Value:service_request' => 'Vraag om hulp',
	'Class:BuildingRequest/Attribute:request_type/Value:service_request+' => 'Service request',
	'Class:BuildingRequest/Attribute:impact' => 'Impact',
	'Class:BuildingRequest/Attribute:impact+' => '',
	'Class:BuildingRequest/Attribute:impact/Value:1' => 'Een afdeling',
	'Class:BuildingRequest/Attribute:impact/Value:1+' => '',
	'Class:BuildingRequest/Attribute:impact/Value:2' => 'Een dienst',
	'Class:BuildingRequest/Attribute:impact/Value:2+' => '',
	'Class:BuildingRequest/Attribute:impact/Value:3' => 'Een persoon',
	'Class:BuildingRequest/Attribute:impact/Value:3+' => '',
	'Class:BuildingRequest/Attribute:priority' => 'Prioriteit',
	'Class:BuildingRequest/Attribute:priority+' => '',
	'Class:BuildingRequest/Attribute:priority/Value:1' => 'kritiek',
	'Class:BuildingRequest/Attribute:priority/Value:1+' => 'kritisch',
	'Class:BuildingRequest/Attribute:priority/Value:2' => 'hoog',
	'Class:BuildingRequest/Attribute:priority/Value:2+' => 'hoog',
	'Class:BuildingRequest/Attribute:priority/Value:3' => 'gemiddeld',
	'Class:BuildingRequest/Attribute:priority/Value:3+' => 'normaal',
	'Class:BuildingRequest/Attribute:priority/Value:4' => 'laag',
	'Class:BuildingRequest/Attribute:priority/Value:4+' => 'laag',
	'Class:BuildingRequest/Attribute:urgency' => 'Urgentie',
	'Class:BuildingRequest/Attribute:urgency+' => '',
	'Class:BuildingRequest/Attribute:urgency/Value:1' => 'kritiek',
	'Class:BuildingRequest/Attribute:urgency/Value:1+' => 'kritisch',
	'Class:BuildingRequest/Attribute:urgency/Value:2' => 'hoog',
	'Class:BuildingRequest/Attribute:urgency/Value:2+' => 'hoog',
	'Class:BuildingRequest/Attribute:urgency/Value:3' => 'gemiddeld',
	'Class:BuildingRequest/Attribute:urgency/Value:3+' => 'normaal',
	'Class:BuildingRequest/Attribute:urgency/Value:4' => 'laag',
	'Class:BuildingRequest/Attribute:urgency/Value:4+' => 'laag',
	'Class:BuildingRequest/Attribute:origin' => 'Oorsprong',
	'Class:BuildingRequest/Attribute:origin+' => '',
	'Class:BuildingRequest/Attribute:origin/Value:mail' => 'mail',
	'Class:BuildingRequest/Attribute:origin/Value:mail+' => 'mail',
	'Class:BuildingRequest/Attribute:origin/Value:monitoring' => 'monitoring',
	'Class:BuildingRequest/Attribute:origin/Value:monitoring+' => 'monitoring',
	'Class:BuildingRequest/Attribute:origin/Value:phone' => 'telefoon',
	'Class:BuildingRequest/Attribute:origin/Value:phone+' => 'telefoon',
	'Class:BuildingRequest/Attribute:origin/Value:portal' => 'portaal',
	'Class:BuildingRequest/Attribute:origin/Value:portal+' => 'portaal',
	'Class:BuildingRequest/Attribute:origin/Value:in_person' => 'op afspraak',
    'Class:BuildingRequest/Attribute:origin/Value:in_person+' => 'op afspraak',
	'Class:BuildingRequest/Attribute:origin/Value:letter' => 'brief',
	'Class:BuildingRequest/Attribute:origin/Value:letter+' => 'brief',
	'Class:BuildingRequest/Attribute:origin/Value:ticket_booth' => 'loket',
	'Class:BuildingRequest/Attribute:origin/Value:ticket_booth+' => 'loket',
	'Class:BuildingRequest/Attribute:approver_id' => 'Goedkeurder',
	'Class:BuildingRequest/Attribute:approver_id+' => '',
	'Class:BuildingRequest/Attribute:approver_email' => 'Goedkeurder Email',
	'Class:BuildingRequest/Attribute:approver_email+' => '',
	'Class:BuildingRequest/Attribute:service_id' => 'Dienst',
	'Class:BuildingRequest/Attribute:service_id+' => '',
	'Class:BuildingRequest/Attribute:service_name' => 'Dienst naam',
	'Class:BuildingRequest/Attribute:service_name+' => '',
	'Class:BuildingRequest/Attribute:servicesubcategory_id' => 'Dienst subcategorie',
	'Class:BuildingRequest/Attribute:servicesubcategory_id+' => '',
	'Class:BuildingRequest/Attribute:servicesubcategory_name' => 'Dienst subcategorie naam',
	'Class:BuildingRequest/Attribute:servicesubcategory_name+' => '',
	'Class:BuildingRequest/Attribute:escalation_flag' => 'Hot Flag',
	'Class:BuildingRequest/Attribute:escalation_flag+' => '',
	'Class:BuildingRequest/Attribute:escalation_flag/Value:no' => 'Nee',
	'Class:BuildingRequest/Attribute:escalation_flag/Value:no+' => 'Nee',
	'Class:BuildingRequest/Attribute:escalation_flag/Value:yes' => 'Ja',
	'Class:BuildingRequest/Attribute:escalation_flag/Value:yes+' => 'Ja',
	'Class:BuildingRequest/Attribute:escalation_reason' => 'Hot reason',
	'Class:BuildingRequest/Attribute:escalation_reason+' => '',
	'Class:BuildingRequest/Attribute:assignment_date' => 'Datum toegewezen',
	'Class:BuildingRequest/Attribute:assignment_date+' => '',
	'Class:BuildingRequest/Attribute:resolution_date' => 'Datum opgelost',
	'Class:BuildingRequest/Attribute:resolution_date+' => '',
	'Class:BuildingRequest/Attribute:last_pending_date' => 'Laatste wachtend datum',
	'Class:BuildingRequest/Attribute:last_pending_date+' => '',
	'Class:BuildingRequest/Attribute:cumulatedpending' => 'samengeteld wachtend',
	'Class:BuildingRequest/Attribute:cumulatedpending+' => '',
	'Class:BuildingRequest/Attribute:tto' => 'TTO',
	'Class:BuildingRequest/Attribute:tto+' => '',
	'Class:BuildingRequest/Attribute:ttr' => 'TTR',
	'Class:BuildingRequest/Attribute:ttr+' => '',
	'Class:BuildingRequest/Attribute:tto_escalation_deadline' => 'TTO Deadline',
	'Class:BuildingRequest/Attribute:tto_escalation_deadline+' => '',
	'Class:BuildingRequest/Attribute:sla_tto_passed' => 'SLA tto passed',
	'Class:BuildingRequest/Attribute:sla_tto_passed+' => '',
	'Class:BuildingRequest/Attribute:sla_tto_over' => 'SLA tto over',
	'Class:BuildingRequest/Attribute:sla_tto_over+' => '',
	'Class:BuildingRequest/Attribute:ttr_escalation_deadline' => 'TTR Deadline',
	'Class:BuildingRequest/Attribute:ttr_escalation_deadline+' => '',
	'Class:BuildingRequest/Attribute:sla_ttr_passed' => 'SLA ttr gepasseerd',
	'Class:BuildingRequest/Attribute:sla_ttr_passed+' => '',
	'Class:BuildingRequest/Attribute:sla_ttr_over' => 'SLA ttr over',
	'Class:BuildingRequest/Attribute:sla_ttr_over+' => '',
	'Class:BuildingRequest/Attribute:time_spent' => 'Resolutie vertraging',
	'Class:BuildingRequest/Attribute:time_spent+' => '',
	'Class:BuildingRequest/Attribute:resolution_code' => 'Resolutie code',
	'Class:BuildingRequest/Attribute:resolution_code+' => '',
	'Class:BuildingRequest/Attribute:resolution_code/Value:assistance' => 'assistentie',
	'Class:BuildingRequest/Attribute:resolution_code/Value:assistance+' => 'assistentie',
	'Class:BuildingRequest/Attribute:resolution_code/Value:bug fixed' => 'bug opgelost',
	'Class:BuildingRequest/Attribute:resolution_code/Value:bug fixed+' => 'bug ogelost',
	'Class:BuildingRequest/Attribute:resolution_code/Value:hardware repair' => 'hardware gerepareerd',
	'Class:BuildingRequest/Attribute:resolution_code/Value:hardware repair+' => 'hardware gerepareerd',
	'Class:BuildingRequest/Attribute:resolution_code/Value:other' => 'andere',
	'Class:BuildingRequest/Attribute:resolution_code/Value:other+' => 'andere',
	'Class:BuildingRequest/Attribute:resolution_code/Value:software patch' => 'software patch',
	'Class:BuildingRequest/Attribute:resolution_code/Value:software patch+' => 'software patch',
	'Class:BuildingRequest/Attribute:resolution_code/Value:system update' => 'systeem update',
	'Class:BuildingRequest/Attribute:resolution_code/Value:system update+' => 'systeem update',
	'Class:BuildingRequest/Attribute:resolution_code/Value:training' => 'training',
	'Class:BuildingRequest/Attribute:resolution_code/Value:training+' => 'training',
	'Class:BuildingRequest/Attribute:solution' => 'Oplossing',
	'Class:BuildingRequest/Attribute:solution+' => '',
	'Class:BuildingRequest/Attribute:pending_reason' => 'Reden waarom het in afwachting staat',
	'Class:BuildingRequest/Attribute:pending_reason+' => '',
	'Class:BuildingRequest/Attribute:parent_request_id' => 'Hoofdticket',
	'Class:BuildingRequest/Attribute:parent_request_id+' => '',
	'Class:BuildingRequest/Attribute:parent_incident_id' => 'Hoofdincident',
	'Class:BuildingRequest/Attribute:parent_incident_id+' => '',
	'Class:BuildingRequest/Attribute:parent_request_ref' => 'Ref request',
	'Class:BuildingRequest/Attribute:parent_request_ref+' => '',
	'Class:BuildingRequest/Attribute:parent_problem_id' => 'Hoofdprobleem',
	'Class:BuildingRequest/Attribute:parent_problem_id+' => '',
	'Class:BuildingRequest/Attribute:parent_problem_ref' => 'Ref probleem',
	'Class:BuildingRequest/Attribute:parent_problem_ref+' => '',
	'Class:BuildingRequest/Attribute:parent_change_id' => 'Hoofdchange',
	'Class:BuildingRequest/Attribute:parent_change_id+' => '',
	'Class:BuildingRequest/Attribute:parent_change_ref' => 'Ref change',
	'Class:BuildingRequest/Attribute:parent_change_ref+' => '',
	'Class:BuildingRequest/Attribute:related_request_list' => 'Sub Tickets',
	'Class:BuildingRequest/Attribute:related_request_list+' => 'Alle tickets die gelinkt zijn aan dit hoofdticket',
	'Class:BuildingRequest/Attribute:public_log' => 'Publiek commentaar',
	'Class:BuildingRequest/Attribute:public_log+' => '',
	'Class:BuildingRequest/Attribute:user_satisfaction' => 'Gebruikerstevredenheid',
	'Class:BuildingRequest/Attribute:user_satisfaction+' => '',
	'Class:BuildingRequest/Attribute:user_satisfaction/Value:1' => 'Zeer tevreden',
	'Class:BuildingRequest/Attribute:user_satisfaction/Value:1+' => 'Zeer tevreden',
	'Class:BuildingRequest/Attribute:user_satisfaction/Value:2' => 'Tamelijk tevreden',
	'Class:BuildingRequest/Attribute:user_satisfaction/Value:2+' => 'Takelijk tevreden',
	'Class:BuildingRequest/Attribute:user_satisfaction/Value:3' => 'Tamelijk ontevreden',
	'Class:BuildingRequest/Attribute:user_satisfaction/Value:3+' => 'Tamelijk ontevreden',
	'Class:BuildingRequest/Attribute:user_satisfaction/Value:4' => 'Zeer ontevreden',
	'Class:BuildingRequest/Attribute:user_satisfaction/Value:4+' => 'Zeer ontevreden',
	'Class:BuildingRequest/Attribute:user_comment' => 'Gebruikersreactie',
	'Class:BuildingRequest/Attribute:user_comment+' => '',
	'Class:BuildingRequest/Attribute:parent_request_id_friendlyname' => 'parent_request_id_friendlyname',
	'Class:BuildingRequest/Attribute:parent_request_id_friendlyname+' => '',
	'Class:BuildingRequest/Stimulus:ev_assign' => 'Wijs toe',
	'Class:BuildingRequest/Stimulus:ev_assign+' => '',
	'Class:BuildingRequest/Stimulus:ev_reassign' => 'Wijs opnieuw toe',
	'Class:BuildingRequest/Stimulus:ev_reassign+' => '',
	'Class:BuildingRequest/Stimulus:ev_approve' => 'Keur goed',
	'Class:BuildingRequest/Stimulus:ev_approve+' => '',
	'Class:BuildingRequest/Stimulus:ev_reject' => 'Keur af',
	'Class:BuildingRequest/Stimulus:ev_reject+' => '',
	'Class:BuildingRequest/Stimulus:ev_pending' => 'In afwachting',
	'Class:BuildingRequest/Stimulus:ev_pending+' => '',
	'Class:BuildingRequest/Stimulus:ev_timeout' => 'Timeout',
	'Class:BuildingRequest/Stimulus:ev_timeout+' => '',
	'Class:BuildingRequest/Stimulus:ev_autoresolve' => 'Automatisch oplossen',
	'Class:BuildingRequest/Stimulus:ev_autoresolve+' => '',
	'Class:BuildingRequest/Stimulus:ev_autoclose' => 'Automatisch sluiten',
	'Class:BuildingRequest/Stimulus:ev_autoclose+' => '',
	'Class:BuildingRequest/Stimulus:ev_resolve' => 'Markeren als opgelost',
	'Class:BuildingRequest/Stimulus:ev_resolve+' => '',
	'Class:BuildingRequest/Stimulus:ev_close' => 'Sluit dit verzoek',
	'Class:BuildingRequest/Stimulus:ev_close+' => '',
	'Class:BuildingRequest/Stimulus:ev_reopen' => 'Her-open',
	'Class:BuildingRequest/Stimulus:ev_reopen+' => '',
	'Class:BuildingRequest/Stimulus:ev_wait_for_approval' => 'Wacht op goedkeuring',
	'Class:BuildingRequest/Stimulus:ev_wait_for_approval+' => '',
	'Class:BuildingRequest/Error:CannotAssignParentRequestIdToSelf' => 'Kan niet toewijzen aan hoofdverzoek en aan het verzoek zelf',

	'Class:BuildingRequest/Method:ResolveChildTickets' => 'ResolveChildTickets',
	'Class:BuildingRequest/Method:ResolveChildTickets+' => 'Cascade the resolution to child requests (ev_autoresolve), and align the following characteristics of the request: service, team, agent, resolution info',
));

