<?php
// Copyright (C) 2010-2014 Combodo SARL
//
//   This file is part of iTop.
//
//   iTop is free software; you can redistribute it and/or modify	
//   it under the terms of the GNU Affero General Public License as published by
//   the Free Software Foundation, either version 3 of the License, or
//   (at your option) any later version.
//
//   iTop is distributed in the hope that it will be useful,
//   but WITHOUT ANY WARRANTY; without even the implied warranty of
//   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//   GNU Affero General Public License for more details.
//
//   You should have received a copy of the GNU Affero General Public License
//   along with iTop. If not, see <http://www.gnu.org/licenses/>


/**
 * Localized data
 *
 * @copyright   Copyright (C) 2010-2012 Combodo SARL
 * @license     http://opensource.org/licenses/AGPL-3.0
 */

Dict::Add('NL NL', 'Dutch', 'Nederlands', array(
	'Menu:SubsidyRequestManagement' => 'Subsidies',
	'Menu:SubsidyRequestManagement+' => 'Subsidies',
	'Menu:SubsidyRequestManagementProvider' => 'Helpdesk leverancier',
	'Menu:SubsidyRequestManagementProvider+' => 'Helpdesk leverancier',
	'Menu:SubsidyRequest:Provider' => 'Open tickets overgebracht naar leverancier',
	'Menu:SubsidyRequest:Provider+' => 'Open tickets overgebracht naar leverancier',
	'Menu:SubsidyRequest:Overview' => 'Overzicht',
	'Menu:SubsidyRequest:Overview+' => 'Subsidie overzicht',
	'Menu:NewSubsidyRequest' => 'Nieuwe subsidie',
	'Menu:NewSubsidyRequest+' => 'Maak een nieuwe subsidie aan',
	'Menu:SearchSubsidyRequests' => 'Zoek naar subsidies',
	'Menu:SearchSubsidyRequests+' => 'Zoek naar subsidies',
	'Menu:SubsidyRequest:Shortcuts' => 'Snelkoppelingen',
	'Menu:SubsidyRequest:Shortcuts+' => '',
	'Menu:SubsidyRequest:MyRequests' => 'Subsidies toegewezen aan mij',
	'Menu:SubsidyRequest:MyRequests+' => 'Subsidies toegewezen aan mij (als agent of clusterverantwoordelijke)',
	'Menu:SubsidyRequest:MySupportRequests' => 'Subsidies van mij',
	'Menu:SubsidyRequest:MySupportRequests+' => 'Subsidies van mij',
	'Menu:SubsidyRequest:EscalatedRequests' => 'Dringende tickets',
	'Menu:SubsidyRequest:EscalatedRequests+' => 'Dringende tickets',
	'Menu:SubsidyRequest:OpenRequests' => 'Alle openstaande subsidies',
	'Menu:SubsidyRequest:OpenRequests+' => 'Alle openstaande subsidies',
	'UI:WelcomeMenu:MyAssignedCalls' => 'Tickets toegewezen aan mij',
	'UI-RequestManagementOverview-RequestByType-last-14-days' => 'Tickets van de afgelopen 14 dagen (per type)',
	'UI-RequestManagementOverview-Last-14-days' => 'Tickets van de afgelopen 14 dagen (per dag)',
	'UI-RequestManagementOverview-OpenRequestByStatus' => 'Open tickets per status',
	'UI-RequestManagementOverview-OpenRequestByAgent' => 'Open tickets per medewerker',
	'UI-RequestManagementOverview-OpenRequestByType' => 'Open tickets per type',
	'UI-RequestManagementOverview-OpenRequestByCustomer' => 'Open tickets per organisatie',
	'Class:SubsidyRequest:KnownErrorList' => 'Bekende fouten',
));

// Dictionnary conventions
// Class:<class_name>
// Class:<class_name>+
// Class:<class_name>/Attribute:<attribute_code>
// Class:<class_name>/Attribute:<attribute_code>+
// Class:<class_name>/Attribute:<attribute_code>/Value:<value>
// Class:<class_name>/Attribute:<attribute_code>/Value:<value>+
// Class:<class_name>/Stimulus:<stimulus_code>
// Class:<class_name>/Stimulus:<stimulus_code>+

//
// Class: SubsidyRequest
//

Dict::Add('NL NL', 'Dutch', 'Nederlands', array(
	'Class:SubsidyRequest' => 'Gebruikerstickets',
	'Class:SubsidyRequest+' => '',
	'Class:SubsidyRequest/Attribute:status' => 'Status',
	'Class:SubsidyRequest/Attribute:status+' => '',
	'Class:SubsidyRequest/Attribute:status/Value:new' => 'Nieuw',
	'Class:SubsidyRequest/Attribute:status/Value:new+' => '',
	'Class:SubsidyRequest/Attribute:status/Value:escalated_tto' => 'Geëscalleerd TTO',
	'Class:SubsidyRequest/Attribute:status/Value:escalated_tto+' => '',
	'Class:SubsidyRequest/Attribute:status/Value:assigned' => 'Toegewezen',
	'Class:SubsidyRequest/Attribute:status/Value:assigned+' => '',
	'Class:SubsidyRequest/Attribute:status/Value:escalated_ttr' => 'Geëscaleerd TTR',
	'Class:SubsidyRequest/Attribute:status/Value:escalated_ttr+' => '',
	'Class:SubsidyRequest/Attribute:status/Value:waiting_for_approval' => 'Wacht op goedkeuring',
	'Class:SubsidyRequest/Attribute:status/Value:waiting_for_approval+' => '',
	'Class:SubsidyRequest/Attribute:status/Value:approved' => 'Goedgekeurd',
	'Class:SubsidyRequest/Attribute:status/Value:approved+' => '',
	'Class:SubsidyRequest/Attribute:status/Value:rejected' => 'Afgewezen',
	'Class:SubsidyRequest/Attribute:status/Value:rejected+' => '',
	'Class:SubsidyRequest/Attribute:status/Value:pending' => 'Wachtend',
	'Class:SubsidyRequest/Attribute:status/Value:pending+' => '',
	'Class:SubsidyRequest/Attribute:status/Value:resolved' => 'Opgelost',
	'Class:SubsidyRequest/Attribute:status/Value:resolved+' => '',
	'Class:SubsidyRequest/Attribute:status/Value:closed' => 'Gesloten',
	'Class:SubsidyRequest/Attribute:status/Value:closed+' => '',
	'Class:SubsidyRequest/Attribute:request_type' => 'Type verzoek',
	'Class:SubsidyRequest/Attribute:request_type+' => '',
	'Class:SubsidyRequest/Attribute:request_type/Value:service_request' => 'Vraag om hulp',
	'Class:SubsidyRequest/Attribute:request_type/Value:service_request+' => 'Service request',
	'Class:SubsidyRequest/Attribute:impact' => 'Impact',
	'Class:SubsidyRequest/Attribute:impact+' => '',
	'Class:SubsidyRequest/Attribute:impact/Value:1' => 'Een afdeling',
	'Class:SubsidyRequest/Attribute:impact/Value:1+' => '',
	'Class:SubsidyRequest/Attribute:impact/Value:2' => 'Een dienst',
	'Class:SubsidyRequest/Attribute:impact/Value:2+' => '',
	'Class:SubsidyRequest/Attribute:impact/Value:3' => 'Een persoon',
	'Class:SubsidyRequest/Attribute:impact/Value:3+' => '',
	'Class:SubsidyRequest/Attribute:priority' => 'Prioriteit',
	'Class:SubsidyRequest/Attribute:priority+' => '',
	'Class:SubsidyRequest/Attribute:priority/Value:1' => 'kritiek',
	'Class:SubsidyRequest/Attribute:priority/Value:1+' => 'kritisch',
	'Class:SubsidyRequest/Attribute:priority/Value:2' => 'hoog',
	'Class:SubsidyRequest/Attribute:priority/Value:2+' => 'hoog',
	'Class:SubsidyRequest/Attribute:priority/Value:3' => 'gemiddeld',
	'Class:SubsidyRequest/Attribute:priority/Value:3+' => 'normaal',
	'Class:SubsidyRequest/Attribute:priority/Value:4' => 'laag',
	'Class:SubsidyRequest/Attribute:priority/Value:4+' => 'laag',
	'Class:SubsidyRequest/Attribute:urgency' => 'Urgentie',
	'Class:SubsidyRequest/Attribute:urgency+' => '',
	'Class:SubsidyRequest/Attribute:urgency/Value:1' => 'kritiek',
	'Class:SubsidyRequest/Attribute:urgency/Value:1+' => 'kritisch',
	'Class:SubsidyRequest/Attribute:urgency/Value:2' => 'hoog',
	'Class:SubsidyRequest/Attribute:urgency/Value:2+' => 'hoog',
	'Class:SubsidyRequest/Attribute:urgency/Value:3' => 'gemiddeld',
	'Class:SubsidyRequest/Attribute:urgency/Value:3+' => 'normaal',
	'Class:SubsidyRequest/Attribute:urgency/Value:4' => 'laag',
	'Class:SubsidyRequest/Attribute:urgency/Value:4+' => 'laag',
	'Class:SubsidyRequest/Attribute:origin' => 'Oorsprong',
	'Class:SubsidyRequest/Attribute:origin+' => '',
	'Class:SubsidyRequest/Attribute:origin/Value:mail' => 'mail',
	'Class:SubsidyRequest/Attribute:origin/Value:mail+' => 'mail',
	'Class:SubsidyRequest/Attribute:origin/Value:monitoring' => 'monitoring',
	'Class:SubsidyRequest/Attribute:origin/Value:monitoring+' => 'monitoring',
	'Class:SubsidyRequest/Attribute:origin/Value:phone' => 'telefoon',
	'Class:SubsidyRequest/Attribute:origin/Value:phone+' => 'telefoon',
	'Class:SubsidyRequest/Attribute:origin/Value:portal' => 'portaal',
	'Class:SubsidyRequest/Attribute:origin/Value:portal+' => 'portaal',
	'Class:SubsidyRequest/Attribute:origin/Value:in_person' => 'in persoon',
    'Class:SubsidyRequest/Attribute:origin/Value:in_person+' => 'in persoon',
	'Class:SubsidyRequest/Attribute:approver_id' => 'Goedkeurder',
	'Class:SubsidyRequest/Attribute:approver_id+' => '',
	'Class:SubsidyRequest/Attribute:approver_email' => 'Goedkeurder Email',
	'Class:SubsidyRequest/Attribute:approver_email+' => '',
	'Class:SubsidyRequest/Attribute:service_id' => 'Dienst',
	'Class:SubsidyRequest/Attribute:service_id+' => '',
	'Class:SubsidyRequest/Attribute:service_name' => 'Dienst naam',
	'Class:SubsidyRequest/Attribute:service_name+' => '',
	'Class:SubsidyRequest/Attribute:servicesubcategory_id' => 'Dienst subcategorie',
	'Class:SubsidyRequest/Attribute:servicesubcategory_id+' => '',
	'Class:SubsidyRequest/Attribute:servicesubcategory_name' => 'Dienst subcategorie naam',
	'Class:SubsidyRequest/Attribute:servicesubcategory_name+' => '',
	'Class:SubsidyRequest/Attribute:escalation_flag' => 'Hot Flag',
	'Class:SubsidyRequest/Attribute:escalation_flag+' => '',
	'Class:SubsidyRequest/Attribute:escalation_flag/Value:no' => 'Nee',
	'Class:SubsidyRequest/Attribute:escalation_flag/Value:no+' => 'Nee',
	'Class:SubsidyRequest/Attribute:escalation_flag/Value:yes' => 'Ja',
	'Class:SubsidyRequest/Attribute:escalation_flag/Value:yes+' => 'Ja',
	'Class:SubsidyRequest/Attribute:escalation_reason' => 'Hot reason',
	'Class:SubsidyRequest/Attribute:escalation_reason+' => '',
	'Class:SubsidyRequest/Attribute:assignment_date' => 'Datum toegewezen',
	'Class:SubsidyRequest/Attribute:assignment_date+' => '',
	'Class:SubsidyRequest/Attribute:resolution_date' => 'Datum opgelost',
	'Class:SubsidyRequest/Attribute:resolution_date+' => '',
	'Class:SubsidyRequest/Attribute:last_pending_date' => 'Laatste wachtend datum',
	'Class:SubsidyRequest/Attribute:last_pending_date+' => '',
	'Class:SubsidyRequest/Attribute:cumulatedpending' => 'samengeteld wachtend',
	'Class:SubsidyRequest/Attribute:cumulatedpending+' => '',
	'Class:SubsidyRequest/Attribute:tto' => 'TTO',
	'Class:SubsidyRequest/Attribute:tto+' => '',
	'Class:SubsidyRequest/Attribute:ttr' => 'TTR',
	'Class:SubsidyRequest/Attribute:ttr+' => '',
	'Class:SubsidyRequest/Attribute:tto_escalation_deadline' => 'TTO Deadline',
	'Class:SubsidyRequest/Attribute:tto_escalation_deadline+' => '',
	'Class:SubsidyRequest/Attribute:sla_tto_passed' => 'SLA tto passed',
	'Class:SubsidyRequest/Attribute:sla_tto_passed+' => '',
	'Class:SubsidyRequest/Attribute:sla_tto_over' => 'SLA tto over',
	'Class:SubsidyRequest/Attribute:sla_tto_over+' => '',
	'Class:SubsidyRequest/Attribute:ttr_escalation_deadline' => 'TTR Deadline',
	'Class:SubsidyRequest/Attribute:ttr_escalation_deadline+' => '',
	'Class:SubsidyRequest/Attribute:sla_ttr_passed' => 'SLA ttr gepasseerd',
	'Class:SubsidyRequest/Attribute:sla_ttr_passed+' => '',
	'Class:SubsidyRequest/Attribute:sla_ttr_over' => 'SLA ttr over',
	'Class:SubsidyRequest/Attribute:sla_ttr_over+' => '',
	'Class:SubsidyRequest/Attribute:time_spent' => 'Resolutie vertraging',
	'Class:SubsidyRequest/Attribute:time_spent+' => '',
	'Class:SubsidyRequest/Attribute:resolution_code' => 'Resolutie code',
	'Class:SubsidyRequest/Attribute:resolution_code+' => '',
	'Class:SubsidyRequest/Attribute:resolution_code/Value:assistance' => 'assistentie',
	'Class:SubsidyRequest/Attribute:resolution_code/Value:assistance+' => 'assistentie',
	'Class:SubsidyRequest/Attribute:resolution_code/Value:bug fixed' => 'bug opgelost',
	'Class:SubsidyRequest/Attribute:resolution_code/Value:bug fixed+' => 'bug ogelost',
	'Class:SubsidyRequest/Attribute:resolution_code/Value:hardware repair' => 'hardware gerepareerd',
	'Class:SubsidyRequest/Attribute:resolution_code/Value:hardware repair+' => 'hardware gerepareerd',
	'Class:SubsidyRequest/Attribute:resolution_code/Value:other' => 'andere',
	'Class:SubsidyRequest/Attribute:resolution_code/Value:other+' => 'andere',
	'Class:SubsidyRequest/Attribute:resolution_code/Value:software patch' => 'software patch',
	'Class:SubsidyRequest/Attribute:resolution_code/Value:software patch+' => 'software patch',
	'Class:SubsidyRequest/Attribute:resolution_code/Value:system update' => 'systeem update',
	'Class:SubsidyRequest/Attribute:resolution_code/Value:system update+' => 'systeem update',
	'Class:SubsidyRequest/Attribute:resolution_code/Value:training' => 'training',
	'Class:SubsidyRequest/Attribute:resolution_code/Value:training+' => 'training',
	'Class:SubsidyRequest/Attribute:solution' => 'Oplossing',
	'Class:SubsidyRequest/Attribute:solution+' => '',
	'Class:SubsidyRequest/Attribute:pending_reason' => 'Reden waarom het in afwachting staat',
	'Class:SubsidyRequest/Attribute:pending_reason+' => '',
	'Class:SubsidyRequest/Attribute:parent_request_id' => 'Hoofdticket',
	'Class:SubsidyRequest/Attribute:parent_request_id+' => '',
	'Class:SubsidyRequest/Attribute:parent_incident_id' => 'Hoofdincident',
	'Class:SubsidyRequest/Attribute:parent_incident_id+' => '',
	'Class:SubsidyRequest/Attribute:parent_request_ref' => 'Ref request',
	'Class:SubsidyRequest/Attribute:parent_request_ref+' => '',
	'Class:SubsidyRequest/Attribute:parent_problem_id' => 'Hoofdprobleem',
	'Class:SubsidyRequest/Attribute:parent_problem_id+' => '',
	'Class:SubsidyRequest/Attribute:parent_problem_ref' => 'Ref probleem',
	'Class:SubsidyRequest/Attribute:parent_problem_ref+' => '',
	'Class:SubsidyRequest/Attribute:parent_change_id' => 'Hoofdchange',
	'Class:SubsidyRequest/Attribute:parent_change_id+' => '',
	'Class:SubsidyRequest/Attribute:parent_change_ref' => 'Ref change',
	'Class:SubsidyRequest/Attribute:parent_change_ref+' => '',
	'Class:SubsidyRequest/Attribute:related_request_list' => 'Sub Tickets',
	'Class:SubsidyRequest/Attribute:related_request_list+' => 'Alle tickets die gelinkt zijn aan dit hoofdticket',
	'Class:SubsidyRequest/Attribute:public_log' => 'Publiek commentaar',
	'Class:SubsidyRequest/Attribute:public_log+' => '',
	'Class:SubsidyRequest/Attribute:private_log' => 'Privé commentaar',
	'Class:SubsidyRequest/Attribute:private_log+' => '',
	'Class:SubsidyRequest/Attribute:user_satisfaction' => 'Gebruikerstevredenheid',
	'Class:SubsidyRequest/Attribute:user_satisfaction+' => '',
	'Class:SubsidyRequest/Attribute:user_satisfaction/Value:1' => 'Zeer tevreden',
	'Class:SubsidyRequest/Attribute:user_satisfaction/Value:1+' => 'Zeer tevreden',
	'Class:SubsidyRequest/Attribute:user_satisfaction/Value:2' => 'Tamelijk tevreden',
	'Class:SubsidyRequest/Attribute:user_satisfaction/Value:2+' => 'Takelijk tevreden',
	'Class:SubsidyRequest/Attribute:user_satisfaction/Value:3' => 'Tamelijk ontevreden',
	'Class:SubsidyRequest/Attribute:user_satisfaction/Value:3+' => 'Tamelijk ontevreden',
	'Class:SubsidyRequest/Attribute:user_satisfaction/Value:4' => 'Zeer ontevreden',
	'Class:SubsidyRequest/Attribute:user_satisfaction/Value:4+' => 'Zeer ontevreden',
	'Class:SubsidyRequest/Attribute:user_comment' => 'Gebruikersreactie',
	'Class:SubsidyRequest/Attribute:user_comment+' => '',
	'Class:SubsidyRequest/Attribute:parent_request_id_friendlyname' => 'parent_request_id_friendlyname',
	'Class:SubsidyRequest/Attribute:parent_request_id_friendlyname+' => '',
	'Class:SubsidyRequest/Attribute:instance_id' => 'Instantie',
	'Class:SubsidyRequest/Attribute:instance_id+' => 'Van welke instantie komt de subsidie',
	'Class:SubsidyRequest/Attribute:entity_id' => 'Entiteit',
	'Class:SubsidyRequest/Attribute:entity_id+' => 'Voor welke entiteit is deze subsidie',
	'Class:SubsidyRequest/Attribute:manager_id' => 'Verantwoordelijke',
	'Class:SubsidyRequest/Attribute:manager_id+' => 'Clusterverantwoordelijke',
	'Class:SubsidyRequest/Attribute:deposit' => 'Voorschot',
	'Class:SubsidyRequest/Attribute:deposit+' => '',
	'Class:SubsidyRequest/Attribute:expecteddepositdate' => 'Verwachte betalingsdatum',
	'Class:SubsidyRequest/Attribute:expecteddepositdate+' => '',
	'Class:SubsidyRequest/Attribute:depositdate' => 'Effectieve betalingsdatum',
	'Class:SubsidyRequest/Attribute:depositdate+' => '',
	'Class:SubsidyRequest/Attribute:payment' => 'Afrekening',
	'Class:SubsidyRequest/Attribute:payment+' => '',
	'Class:SubsidyRequest/Attribute:expectedpaymentdate' => 'Verwachte afrekeningsdatum',
	'Class:SubsidyRequest/Attribute:expectedpaymentdate+' => '',
	'Class:SubsidyRequest/Attribute:paymentdate' => 'Effectieve afrekeningsdatum',
	'Class:SubsidyRequest/Attribute:paymentdate+' => '',
	'Class:SubsidyRequest/Attribute:budgetpost_account' => 'Algemene rekening',
	'Class:SubsidyRequest/Attribute:budgetpost_account+' => 'budgetpost/alg rek',
	'Class:SubsidyRequest/Attribute:budgetpost_policyitem' => 'Beleidsitem',
	'Class:SubsidyRequest/Attribute:budgetpost_policyitem+' => 'budgetpost/beleidsitem',
	'Class:SubsidyRequest/Attribute:total' => 'Totaal bedrag',
	'Class:SubsidyRequest/Attribute:total+' => '',
	'Class:SubsidyRequest/Attribute:id_agenda_item' => 'Agendanummer',
	'Class:SubsidyRequest/Attribute:id_agenda_item+' => 'Nummer van het agendapunt in Cobra',
	'Class:SubsidyRequest/Attribute:communicationhistory' => 'Historiek communicatie',
	'Class:SubsidyRequest/Attribute:communicationhistory+' => '',
	'Class:SubsidyRequest/Attribute:paymentterms' => 'Voorwaarde uitbetaling',
	'Class:SubsidyRequest/Attribute:paymentterms+' => '',
	'Class:SubsidyRequest/Attribute:private_log' => 'Algemene voorwaarden',
	'Class:SubsidyRequest/Attribute:private_log+' => 'algemene voorwaarden om in aanmerking te komen',
	'Class:SubsidyRequest/Attribute:external_ref' => 'Referentie',
	'Class:SubsidyRequest/Attribute:external_ref+' => 'Referentienummer dat je gekregen hebt van de instantie',
	'Ticket:financial' => 'Financieel',
	'Ticket:financial+' => '',
	
	
	
	'Class:SubsidyRequest/Stimulus:ev_assign' => 'Wijs toe',
	'Class:SubsidyRequest/Stimulus:ev_assign+' => '',
	'Class:SubsidyRequest/Stimulus:ev_reassign' => 'Wijs opnieuw toe',
	'Class:SubsidyRequest/Stimulus:ev_reassign+' => '',
	'Class:SubsidyRequest/Stimulus:ev_approve' => 'Keur goed',
	'Class:SubsidyRequest/Stimulus:ev_approve+' => '',
	'Class:SubsidyRequest/Stimulus:ev_reject' => 'Keur af',
	'Class:SubsidyRequest/Stimulus:ev_reject+' => '',
	'Class:SubsidyRequest/Stimulus:ev_pending' => 'In afwachting',
	'Class:SubsidyRequest/Stimulus:ev_pending+' => '',
	'Class:SubsidyRequest/Stimulus:ev_timeout' => 'Timeout',
	'Class:SubsidyRequest/Stimulus:ev_timeout+' => '',
	'Class:SubsidyRequest/Stimulus:ev_autoresolve' => 'Automatisch oplossen',
	'Class:SubsidyRequest/Stimulus:ev_autoresolve+' => '',
	'Class:SubsidyRequest/Stimulus:ev_autoclose' => 'Automatisch sluiten',
	'Class:SubsidyRequest/Stimulus:ev_autoclose+' => '',
	'Class:SubsidyRequest/Stimulus:ev_resolve' => 'Markeren als opgelost',
	'Class:SubsidyRequest/Stimulus:ev_resolve+' => '',
	'Class:SubsidyRequest/Stimulus:ev_close' => 'Sluit dit verzoek',
	'Class:SubsidyRequest/Stimulus:ev_close+' => '',
	'Class:SubsidyRequest/Stimulus:ev_reopen' => 'Her-open',
	'Class:SubsidyRequest/Stimulus:ev_reopen+' => '',
	'Class:SubsidyRequest/Stimulus:ev_wait_for_approval' => 'Wacht op goedkeuring',
	'Class:SubsidyRequest/Stimulus:ev_wait_for_approval+' => '',
	'Class:SubsidyRequest/Error:CannotAssignParentRequestIdToSelf' => 'Kan niet toewijzen aan hoofdverzoek en aan het verzoek zelf',
	'Class:SubsidyRequest/Attribute:reminder' => 'Herinnering',
	'Class:SubsidyRequest/Attribute:reminder+' => 'Herinnering',	

	'Class:SubsidyRequest/Method:ResolveChildTickets' => 'ResolveChildTickets',
	'Class:SubsidyRequest/Method:ResolveChildTickets+' => 'Cascade the resolution to child requests (ev_autoresolve), and align the following characteristics of the request: service, team, agent, resolution info',
));
