<?php
// Copyright (C) 2010-2014 Combodo SARL
//
//   This file is part of iTop.
//
//   iTop is free software; you can redistribute it and/or modify	
//   it under the terms of the GNU Affero General Public License as published by
//   the Free Software Foundation, either version 3 of the License, or
//   (at your option) any later version.
//
//   iTop is distributed in the hope that it will be useful,
//   but WITHOUT ANY WARRANTY; without even the implied warranty of
//   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//   GNU Affero General Public License for more details.
//
//   You should have received a copy of the GNU Affero General Public License
//   along with iTop. If not, see <http://www.gnu.org/licenses/>


/**
 * Localized data
 *
 * @copyright   Copyright (C) 2010-2012 Combodo SARL
 * @license     http://opensource.org/licenses/AGPL-3.0
 */

Dict::Add('NL NL', 'Dutch', 'Nederlands', array(
	'Menu:ComRequestManagement' => 'Communicatie',
	'Menu:ComRequestManagement+' => 'Communicatie',
	'Menu:ComRequestManagementProvider' => 'Helpdesk leverancier',
	'Menu:ComRequestManagementProvider+' => 'Helpdesk leverancier',
	'Menu:ComRequest:Provider' => 'Open tickets overgebracht naar leverancier',
	'Menu:ComRequest:Provider+' => 'Open tickets overgebracht naar leverancier',
	'Menu:ComRequest:Overview' => 'Overzicht',
	'Menu:ComRequest:Overview+' => 'Communicatie-overzicht',
	'Menu:NewComRequest' => 'Nieuw ticket',
	'Menu:NewComRequest+' => 'Maak een nieuw ticket aan',
	'Menu:SearchComRequests' => 'Zoek naar tickets',
	'Menu:SearchComRequests+' => 'Zoek naar tickets',
	'Menu:ComRequest:Shortcuts' => 'Snelkoppelingen',
	'Menu:ComRequest:Shortcuts+' => '',
	'Menu:ComRequest:MyRequests' => 'Tickets toegewezen aan mij',
	'Menu:ComRequest:MyRequests+' => 'Tickets toegewezen aan mij (als behandelaar)',
	'Menu:ComRequest:MySupportRequests' => 'Tickets van mij',
	'Menu:ComRequest:MySupportRequests+' => 'Tickets van mij',
	'Menu:ComRequest:EscalatedRequests' => 'Dringende tickets',
	'Menu:ComRequest:EscalatedRequests+' => 'Dringende tickets',
	'Menu:ComRequest:OpenRequests' => 'Alle openstaande tickets',
	'Menu:ComRequest:OpenRequests+' => 'Alle openstaande tickets',
	'UI:WelcomeMenu:MyAssignedCalls' => 'Tickets toegewezen aan mij',
	'UI-RequestManagementOverview-RequestByType-last-14-days' => 'Tickets van de afgelopen 14 dagen (per type)',
	'UI-RequestManagementOverview-Last-14-days' => 'Tickets van de afgelopen 14 dagen (per dag)',
	'UI-RequestManagementOverview-OpenRequestByStatus' => 'Open tickets per status',
	'UI-RequestManagementOverview-OpenRequestByAgent' => 'Open tickets per medewerker',
	'UI-RequestManagementOverview-OpenRequestByType' => 'Open tickets per type',
	'UI-RequestManagementOverview-OpenRequestByCustomer' => 'Open tickets per organisatie',
	'Class:ComRequest:KnownErrorList' => 'Bekende fouten',
));

// Dictionnary conventions
// Class:<class_name>
// Class:<class_name>+
// Class:<class_name>/Attribute:<attribute_code>
// Class:<class_name>/Attribute:<attribute_code>+
// Class:<class_name>/Attribute:<attribute_code>/Value:<value>
// Class:<class_name>/Attribute:<attribute_code>/Value:<value>+
// Class:<class_name>/Stimulus:<stimulus_code>
// Class:<class_name>/Stimulus:<stimulus_code>+

//
// Class: ComRequest
//

Dict::Add('NL NL', 'Dutch', 'Nederlands', array(
	'Class:ComRequest' => 'Gebruikerstickets',
	'Class:ComRequest+' => 'Tickets voor Elke',
	'Class:ComRequest/Attribute:status' => 'Status',
	'Class:ComRequest/Attribute:status+' => '',
	'Class:ComRequest/Attribute:status/Value:new' => 'Nieuw',
	'Class:ComRequest/Attribute:status/Value:new+' => '',
	'Class:ComRequest/Attribute:status/Value:escalated_tto' => 'Geëscalleerd TTO',
	'Class:ComRequest/Attribute:status/Value:escalated_tto+' => '',
	'Class:ComRequest/Attribute:status/Value:assigned' => 'Toegewezen',
	'Class:ComRequest/Attribute:status/Value:assigned+' => '',
	'Class:ComRequest/Attribute:status/Value:escalated_ttr' => 'Geëscaleerd TTR',
	'Class:ComRequest/Attribute:status/Value:escalated_ttr+' => '',
	'Class:ComRequest/Attribute:status/Value:waiting_for_approval' => 'Wacht op goedkeuring',
	'Class:ComRequest/Attribute:status/Value:waiting_for_approval+' => '',
	'Class:ComRequest/Attribute:status/Value:approved' => 'Goedgekeurd',
	'Class:ComRequest/Attribute:status/Value:approved+' => '',
	'Class:ComRequest/Attribute:status/Value:rejected' => 'Afgewezen',
	'Class:ComRequest/Attribute:status/Value:rejected+' => '',
	'Class:ComRequest/Attribute:status/Value:pending' => 'Wachtend',
	'Class:ComRequest/Attribute:status/Value:pending+' => '',
	'Class:ComRequest/Attribute:status/Value:resolved' => 'Opgelost',
	'Class:ComRequest/Attribute:status/Value:resolved+' => '',
	'Class:ComRequest/Attribute:status/Value:closed' => 'Gesloten',
	'Class:ComRequest/Attribute:status/Value:closed+' => '',
	'Class:ComRequest/Attribute:request_type' => 'Type verzoek',
	'Class:ComRequest/Attribute:request_type+' => '',
	'Class:ComRequest/Attribute:request_type/Value:service_request' => 'Vraag om hulp',
	'Class:ComRequest/Attribute:request_type/Value:service_request+' => 'Service request',
	'Class:ComRequest/Attribute:impact' => 'Impact',
	'Class:ComRequest/Attribute:impact+' => '',
	'Class:ComRequest/Attribute:impact/Value:1' => 'Een afdeling',
	'Class:ComRequest/Attribute:impact/Value:1+' => '',
	'Class:ComRequest/Attribute:impact/Value:2' => 'Een dienst',
	'Class:ComRequest/Attribute:impact/Value:2+' => '',
	'Class:ComRequest/Attribute:impact/Value:3' => 'Een persoon',
	'Class:ComRequest/Attribute:impact/Value:3+' => '',
	'Class:ComRequest/Attribute:priority' => 'Prioriteit',
	'Class:ComRequest/Attribute:priority+' => '',
	'Class:ComRequest/Attribute:priority/Value:1' => 'kritiek',
	'Class:ComRequest/Attribute:priority/Value:1+' => 'kritisch',
	'Class:ComRequest/Attribute:priority/Value:2' => 'hoog',
	'Class:ComRequest/Attribute:priority/Value:2+' => 'hoog',
	'Class:ComRequest/Attribute:priority/Value:3' => 'gemiddeld',
	'Class:ComRequest/Attribute:priority/Value:3+' => 'normaal',
	'Class:ComRequest/Attribute:priority/Value:4' => 'laag',
	'Class:ComRequest/Attribute:priority/Value:4+' => 'laag',
	'Class:ComRequest/Attribute:urgency' => 'Urgentie',
	'Class:ComRequest/Attribute:urgency+' => '',
	'Class:ComRequest/Attribute:urgency/Value:1' => 'kritiek',
	'Class:ComRequest/Attribute:urgency/Value:1+' => 'kritisch',
	'Class:ComRequest/Attribute:urgency/Value:2' => 'hoog',
	'Class:ComRequest/Attribute:urgency/Value:2+' => 'hoog',
	'Class:ComRequest/Attribute:urgency/Value:3' => 'gemiddeld',
	'Class:ComRequest/Attribute:urgency/Value:3+' => 'normaal',
	'Class:ComRequest/Attribute:urgency/Value:4' => 'laag',
	'Class:ComRequest/Attribute:urgency/Value:4+' => 'laag',
	'Class:ComRequest/Attribute:origin' => 'Oorsprong',
	'Class:ComRequest/Attribute:origin+' => '',
	'Class:ComRequest/Attribute:origin/Value:mail' => 'mail',
	'Class:ComRequest/Attribute:origin/Value:mail+' => 'mail',
	'Class:ComRequest/Attribute:origin/Value:monitoring' => 'monitoring',
	'Class:ComRequest/Attribute:origin/Value:monitoring+' => 'monitoring',
	'Class:ComRequest/Attribute:origin/Value:phone' => 'telefoon',
	'Class:ComRequest/Attribute:origin/Value:phone+' => 'telefoon',
	'Class:ComRequest/Attribute:origin/Value:portal' => 'portaal',
	'Class:ComRequest/Attribute:origin/Value:portal+' => 'portaal',
	'Class:ComRequest/Attribute:origin/Value:in_person' => 'in persoon',
    'Class:ComRequest/Attribute:origin/Value:in_person+' => 'in persoon',
	'Class:ComRequest/Attribute:approver_id' => 'Goedkeurder',
	'Class:ComRequest/Attribute:approver_id+' => '',
	'Class:ComRequest/Attribute:approver_email' => 'Goedkeurder Email',
	'Class:ComRequest/Attribute:approver_email+' => '',
	'Class:ComRequest/Attribute:service_id' => 'Dienst',
	'Class:ComRequest/Attribute:service_id+' => '',
	'Class:ComRequest/Attribute:service_name' => 'Dienst naam',
	'Class:ComRequest/Attribute:service_name+' => '',
	'Class:ComRequest/Attribute:servicesubcategory_id' => 'Dienst subcategorie',
	'Class:ComRequest/Attribute:servicesubcategory_id+' => '',
	'Class:ComRequest/Attribute:servicesubcategory_name' => 'Dienst subcategorie naam',
	'Class:ComRequest/Attribute:servicesubcategory_name+' => '',
	'Class:ComRequest/Attribute:escalation_flag' => 'Hot Flag',
	'Class:ComRequest/Attribute:escalation_flag+' => '',
	'Class:ComRequest/Attribute:escalation_flag/Value:no' => 'Nee',
	'Class:ComRequest/Attribute:escalation_flag/Value:no+' => 'Nee',
	'Class:ComRequest/Attribute:escalation_flag/Value:yes' => 'Ja',
	'Class:ComRequest/Attribute:escalation_flag/Value:yes+' => 'Ja',
	'Class:ComRequest/Attribute:escalation_reason' => 'Hot reason',
	'Class:ComRequest/Attribute:escalation_reason+' => '',
	'Class:ComRequest/Attribute:assignment_date' => 'Datum toegewezen',
	'Class:ComRequest/Attribute:assignment_date+' => '',
	'Class:ComRequest/Attribute:resolution_date' => 'Datum opgelost',
	'Class:ComRequest/Attribute:resolution_date+' => '',
	'Class:ComRequest/Attribute:last_pending_date' => 'Laatste wachtend datum',
	'Class:ComRequest/Attribute:last_pending_date+' => '',
	'Class:ComRequest/Attribute:cumulatedpending' => 'samengeteld wachtend',
	'Class:ComRequest/Attribute:cumulatedpending+' => '',
	'Class:ComRequest/Attribute:tto' => 'TTO',
	'Class:ComRequest/Attribute:tto+' => '',
	'Class:ComRequest/Attribute:ttr' => 'TTR',
	'Class:ComRequest/Attribute:ttr+' => '',
	'Class:ComRequest/Attribute:tto_escalation_deadline' => 'TTO Deadline',
	'Class:ComRequest/Attribute:tto_escalation_deadline+' => '',
	'Class:ComRequest/Attribute:sla_tto_passed' => 'SLA tto passed',
	'Class:ComRequest/Attribute:sla_tto_passed+' => '',
	'Class:ComRequest/Attribute:sla_tto_over' => 'SLA tto over',
	'Class:ComRequest/Attribute:sla_tto_over+' => '',
	'Class:ComRequest/Attribute:ttr_escalation_deadline' => 'TTR Deadline',
	'Class:ComRequest/Attribute:ttr_escalation_deadline+' => '',
	'Class:ComRequest/Attribute:sla_ttr_passed' => 'SLA ttr gepasseerd',
	'Class:ComRequest/Attribute:sla_ttr_passed+' => '',
	'Class:ComRequest/Attribute:sla_ttr_over' => 'SLA ttr over',
	'Class:ComRequest/Attribute:sla_ttr_over+' => '',
	'Class:ComRequest/Attribute:time_spent' => 'Resolutie vertraging',
	'Class:ComRequest/Attribute:time_spent+' => '',
	'Class:ComRequest/Attribute:resolution_code' => 'Resolutie code',
	'Class:ComRequest/Attribute:resolution_code+' => '',
	'Class:ComRequest/Attribute:resolution_code/Value:assistance' => 'assistentie',
	'Class:ComRequest/Attribute:resolution_code/Value:assistance+' => 'assistentie',
	'Class:ComRequest/Attribute:resolution_code/Value:bug fixed' => 'bug opgelost',
	'Class:ComRequest/Attribute:resolution_code/Value:bug fixed+' => 'bug ogelost',
	'Class:ComRequest/Attribute:resolution_code/Value:hardware repair' => 'hardware gerepareerd',
	'Class:ComRequest/Attribute:resolution_code/Value:hardware repair+' => 'hardware gerepareerd',
	'Class:ComRequest/Attribute:resolution_code/Value:other' => 'andere',
	'Class:ComRequest/Attribute:resolution_code/Value:other+' => 'andere',
	'Class:ComRequest/Attribute:resolution_code/Value:software patch' => 'software patch',
	'Class:ComRequest/Attribute:resolution_code/Value:software patch+' => 'software patch',
	'Class:ComRequest/Attribute:resolution_code/Value:system update' => 'systeem update',
	'Class:ComRequest/Attribute:resolution_code/Value:system update+' => 'systeem update',
	'Class:ComRequest/Attribute:resolution_code/Value:training' => 'training',
	'Class:ComRequest/Attribute:resolution_code/Value:training+' => 'training',
	'Class:ComRequest/Attribute:solution' => 'Oplossing',
	'Class:ComRequest/Attribute:solution+' => '',
	'Class:ComRequest/Attribute:pending_reason' => 'Reden waarom het in afwachting staat',
	'Class:ComRequest/Attribute:pending_reason+' => '',
	'Class:ComRequest/Attribute:parent_request_id' => 'Hoofdticket',
	'Class:ComRequest/Attribute:parent_request_id+' => '',
	'Class:ComRequest/Attribute:parent_incident_id' => 'Hoofdincident',
	'Class:ComRequest/Attribute:parent_incident_id+' => '',
	'Class:ComRequest/Attribute:parent_request_ref' => 'Ref request',
	'Class:ComRequest/Attribute:parent_request_ref+' => '',
	'Class:ComRequest/Attribute:parent_problem_id' => 'Hoofdprobleem',
	'Class:ComRequest/Attribute:parent_problem_id+' => '',
	'Class:ComRequest/Attribute:parent_problem_ref' => 'Ref probleem',
	'Class:ComRequest/Attribute:parent_problem_ref+' => '',
	'Class:ComRequest/Attribute:parent_change_id' => 'Hoofdchange',
	'Class:ComRequest/Attribute:parent_change_id+' => '',
	'Class:ComRequest/Attribute:parent_change_ref' => 'Ref change',
	'Class:ComRequest/Attribute:parent_change_ref+' => '',
	'Class:ComRequest/Attribute:related_request_list' => 'Sub Tickets',
	'Class:ComRequest/Attribute:related_request_list+' => 'Alle tickets die gelinkt zijn aan dit hoofdticket',
	'Class:ComRequest/Attribute:public_log' => 'Publiek commentaar',
	'Class:ComRequest/Attribute:public_log+' => '',
	'Class:ComRequest/Attribute:private_log' => 'Privé commentaar',
	'Class:ComRequest/Attribute:private_log+' => '',
	'Class:ComRequest/Attribute:user_satisfaction' => 'Gebruikerstevredenheid',
	'Class:ComRequest/Attribute:user_satisfaction+' => '',
	'Class:ComRequest/Attribute:user_satisfaction/Value:1' => 'Zeer tevreden',
	'Class:ComRequest/Attribute:user_satisfaction/Value:1+' => 'Zeer tevreden',
	'Class:ComRequest/Attribute:user_satisfaction/Value:2' => 'Tamelijk tevreden',
	'Class:ComRequest/Attribute:user_satisfaction/Value:2+' => 'Takelijk tevreden',
	'Class:ComRequest/Attribute:user_satisfaction/Value:3' => 'Tamelijk ontevreden',
	'Class:ComRequest/Attribute:user_satisfaction/Value:3+' => 'Tamelijk ontevreden',
	'Class:ComRequest/Attribute:user_satisfaction/Value:4' => 'Zeer ontevreden',
	'Class:ComRequest/Attribute:user_satisfaction/Value:4+' => 'Zeer ontevreden',
	'Class:ComRequest/Attribute:user_comment' => 'Gebruikersreactie',
	'Class:ComRequest/Attribute:user_comment+' => '',
	'Class:ComRequest/Attribute:parent_request_id_friendlyname' => 'parent_request_id_friendlyname',
	'Class:ComRequest/Attribute:parent_request_id_friendlyname+' => '',
	'Class:ComRequest/Stimulus:ev_assign' => 'Wijs toe',
	'Class:ComRequest/Stimulus:ev_assign+' => '',
	'Class:ComRequest/Stimulus:ev_reassign' => 'Wijs opnieuw toe',
	'Class:ComRequest/Stimulus:ev_reassign+' => '',
	'Class:ComRequest/Stimulus:ev_approve' => 'Keur goed',
	'Class:ComRequest/Stimulus:ev_approve+' => '',
	'Class:ComRequest/Stimulus:ev_reject' => 'Keur af',
	'Class:ComRequest/Stimulus:ev_reject+' => '',
	'Class:ComRequest/Stimulus:ev_pending' => 'In afwachting',
	'Class:ComRequest/Stimulus:ev_pending+' => '',
	'Class:ComRequest/Stimulus:ev_timeout' => 'Timeout',
	'Class:ComRequest/Stimulus:ev_timeout+' => '',
	'Class:ComRequest/Stimulus:ev_autoresolve' => 'Automatisch oplossen',
	'Class:ComRequest/Stimulus:ev_autoresolve+' => '',
	'Class:ComRequest/Stimulus:ev_autoclose' => 'Automatisch sluiten',
	'Class:ComRequest/Stimulus:ev_autoclose+' => '',
	'Class:ComRequest/Stimulus:ev_resolve' => 'Markeren als opgelost',
	'Class:ComRequest/Stimulus:ev_resolve+' => '',
	'Class:ComRequest/Stimulus:ev_close' => 'Sluit dit verzoek',
	'Class:ComRequest/Stimulus:ev_close+' => '',
	'Class:ComRequest/Stimulus:ev_reopen' => 'Her-open',
	'Class:ComRequest/Stimulus:ev_reopen+' => '',
	'Class:ComRequest/Stimulus:ev_wait_for_approval' => 'Wacht op goedkeuring',
	'Class:ComRequest/Stimulus:ev_wait_for_approval+' => '',
	'Class:ComRequest/Error:CannotAssignParentRequestIdToSelf' => 'Kan niet toewijzen aan hoofdverzoek en aan het verzoek zelf',

		
	'Class:ComRequest/Attribute:deadline' => 'Deadline',
	'Class:ComRequest/Attribute:deadline+' => 'Deadline',
	'Class:ComRequest/Attribute:eventdate' => 'Evenementdatum',
	'Class:ComRequest/Attribute:eventdate+' => 'Datum van het evenement',
	'Class:ComRequest/Attribute:poster_A3' => 'Poster A3',
	'Class:ComRequest/Attribute:poster_A3+' => 'Poster A3',	
	'Class:ComRequest/Attribute:poster_A2' => 'Poster A2',
	'Class:ComRequest/Attribute:poster_A2+' => 'Poster A2',
	'Class:ComRequest/Attribute:flyer' => 'Flyer',
	'Class:ComRequest/Attribute:flyer+' => 'Flyer',
	'Class:ComRequest/Attribute:triptych' => 'Drieluik',
	'Class:ComRequest/Attribute:triptych+' => 'Drieluik',
	'Class:ComRequest/Attribute:four_panel' => 'Vierluik',
	'Class:ComRequest/Attribute:four_panel+' => 'Vierluik',
	'Class:ComRequest/Attribute:brochure' => 'Brochure',
	'Class:ComRequest/Attribute:brochure+' => 'Brochure',
	'Class:ComRequest/Attribute:cover_facebook' => 'Facebook omslagfoto',
	'Class:ComRequest/Attribute:cover_facebook+' => 'Facebook omslagfoto',
	'Class:ComRequest/Attribute:cover_event' => 'Facebookevenement omslagfoto',
	'Class:ComRequest/Attribute:cover_event+' => 'Facebookevenement omslagfoto',
	'Class:ComRequest/Attribute:notice_board' => 'Ad valvas',
	'Class:ComRequest/Attribute:notice_board+' => 'Ad valvas',
	'Class:ComRequest/Attribute:graphic_ledwall' => 'Ledwall',
	'Class:ComRequest/Attribute:graphic_ledwall+' => 'Ledwall',
	'Class:ComRequest/Attribute:graphic_screen' => 'Schermen',
	'Class:ComRequest/Attribute:graphic_screen+' => 'Schermen',
	'Class:ComRequest/Attribute:graphic_other' => 'Andere',
	'Class:ComRequest/Attribute:graphic_other+' => 'Andere',
	'Class:ComRequest/Attribute:facebook_city' => 'Facebook',
	'Class:ComRequest/Attribute:facebook_city+' => 'Facebook',
	'Class:ComRequest/Attribute:instagram_city' => 'Instagram',
	'Class:ComRequest/Attribute:instagram_city+' => 'Instagram',
	'Class:ComRequest/Attribute:magazine_city' => 'Izine',
	'Class:ComRequest/Attribute:magazine_city+' => 'Izine',
	'Class:ComRequest/Attribute:ledwall_city' => 'Ledwall',
	'Class:ComRequest/Attribute:ledwall_city+' => 'Ledwall',
	'Class:ComRequest/Attribute:press_city' => 'Pers',
	'Class:ComRequest/Attribute:press_city+' => 'Pers',
	'Class:ComRequest/Attribute:recruitment' => 'Rekrutering',
	'Class:ComRequest/Attribute:recruitment+' => 'Rekrutering',
	'Class:ComRequest/Attribute:screens_city' => 'Schermen',
	'Class:ComRequest/Attribute:screens_city+' => 'Schermen',
	'Class:ComRequest/Attribute:twitter_city' => 'Twitter',
	'Class:ComRequest/Attribute:twitter_city+' => 'Twitter',
	'Class:ComRequest/Attribute:out_database' => 'Uit-databank',
	'Class:ComRequest/Attribute:out_database+' => 'Uit-databank',
	'Class:ComRequest/Attribute:website_city' => 'Website',
	'Class:ComRequest/Attribute:website_city+' => 'Website',
	'Class:ComRequest/Attribute:facebook_library' => 'Facebook bib',
	'Class:ComRequest/Attribute:facebook_library+' => 'Facebook bibliotheek',
	'Class:ComRequest/Attribute:facebook_culture' => 'Facebook De Leest',
	'Class:ComRequest/Attribute:facebook_culture+' => 'Facebook De Leest',
	'Class:ComRequest/Attribute:facebook_museum' => 'Facebook EDO',
	'Class:ComRequest/Attribute:facebook_museum+' => 'Facebook EDO',
	'Class:ComRequest/Attribute:facebook_youth' => 'Facebook jeugd',
	'Class:ComRequest/Attribute:facebook_youth+' => 'Facebook jeugd',
	'Class:ComRequest/Attribute:facebook_sport' => 'Facebook sport',
	'Class:ComRequest/Attribute:facebook_sport+' => 'Facebook sport',
	'Class:ComRequest/Attribute:facebook_market' => 'Facebook zaterdagmarkt',
	'Class:ComRequest/Attribute:facebook_market+' => 'Facebook zaterdagmarkt',
	'Class:ComRequest/Attribute:facebook_homemade' => 'Facebook zelvegemakt',
	'Class:ComRequest/Attribute:facebook_homemade+' => 'Facebook zelvegemakt',
	'Class:ComRequest/Attribute:instagram_museum' => 'Instagram EDO',
	'Class:ComRequest/Attribute:instagram_museum+' => 'Instagram EDO',
	'Class:ComRequest/Attribute:instagram_youth' => 'Instagram jeugd',
	'Class:ComRequest/Attribute:instagram_youth+' => 'Instagram jeugd',
	'Class:ComRequest/Attribute:magazine_youth' => 'Magazine jeugd',
	'Class:ComRequest/Attribute:magazine_youth+' => 'Magazine jeugd',
	'Class:ComRequest/Attribute:twitter_library' => 'Twitter bib',
	'Class:ComRequest/Attribute:twitter_library+' => 'Twitter bibliotheek',
	'Class:ComRequest/Attribute:twitter_youth' => 'Twitter jeugd',
	'Class:ComRequest/Attribute:twitter_youth+' => 'Twitter jeugd',
	'ComRequest:graphical_work' => 'Grafisch werk',
	'ComRequest:graphical_work+' => '',
	'ComRequest:internal_channels' => 'Interne kanalen',
	'ComRequest:internal_channels+' => '',
	'ComRequest:external_channels' => 'Externe kanalen',
	'ComRequest:external_channels+' => '',
	
		
	'Class:ComRequest/Attribute:facebook_city/Value:no' => 'Nee',
	'Class:ComRequest/Attribute:facebook_city/Value:no+' => 'Nee',
	'Class:ComRequest/Attribute:facebook_city/Value:yes' => 'Ja',
	'Class:ComRequest/Attribute:facebook_city/Value:yes+' => 'Ja',
	'Class:ComRequest/Attribute:instagram_city/Value:no' => 'Nee',
	'Class:ComRequest/Attribute:instagram_city/Value:no+' => 'Nee',
	'Class:ComRequest/Attribute:instagram_city/Value:yes' => 'Ja',
	'Class:ComRequest/Attribute:instagram_city/Value:yes+' => 'Ja','Class:ComRequest/Attribute:magazine_city/Value:no' => 'Nee',
	'Class:ComRequest/Attribute:magazine_city/Value:no+' => 'Nee',
	'Class:ComRequest/Attribute:magazine_city/Value:yes' => 'Ja',
	'Class:ComRequest/Attribute:magazine_city/Value:yes+' => 'Ja','Class:ComRequest/Attribute:ledwall_city/Value:no' => 'Nee',
	'Class:ComRequest/Attribute:ledwall_city/Value:no+' => 'Nee',
	'Class:ComRequest/Attribute:ledwall_city/Value:yes' => 'Ja',
	'Class:ComRequest/Attribute:ledwall_city/Value:yes+' => 'Ja','Class:ComRequest/Attribute:press_city/Value:no' => 'Nee',
	'Class:ComRequest/Attribute:press_city/Value:no+' => 'Nee',
	'Class:ComRequest/Attribute:press_city/Value:yes' => 'Ja',
	'Class:ComRequest/Attribute:press_city/Value:yes+' => 'Ja','Class:ComRequest/Attribute:recruitment/Value:no' => 'Nee',
	'Class:ComRequest/Attribute:recruitment/Value:no+' => 'Nee',
	'Class:ComRequest/Attribute:recruitment/Value:yes' => 'Ja',
	'Class:ComRequest/Attribute:recruitment/Value:yes+' => 'Ja',
	'Class:ComRequest/Attribute:screens_city/Value:no' => 'Nee',
	'Class:ComRequest/Attribute:screens_city/Value:no+' => 'Nee',
	'Class:ComRequest/Attribute:screens_city/Value:yes' => 'Ja',
	'Class:ComRequest/Attribute:screens_city/Value:yes+' => 'Ja','Class:ComRequest/Attribute:twitter_city/Value:no' => 'Nee',
	'Class:ComRequest/Attribute:twitter_city/Value:no+' => 'Nee',
	'Class:ComRequest/Attribute:twitter_city/Value:yes' => 'Ja',
	'Class:ComRequest/Attribute:twitter_city/Value:yes+' => 'Ja','Class:ComRequest/Attribute:out_database/Value:no' => 'Nee',
	'Class:ComRequest/Attribute:out_database/Value:no+' => 'Nee',
	'Class:ComRequest/Attribute:out_database/Value:yes' => 'Ja',
	'Class:ComRequest/Attribute:out_database/Value:yes+' => 'Ja','Class:ComRequest/Attribute:website_city/Value:no' => 'Nee',
	'Class:ComRequest/Attribute:website_city/Value:no+' => 'Nee',
	'Class:ComRequest/Attribute:website_city/Value:yes' => 'Ja',
	'Class:ComRequest/Attribute:website_city/Value:yes+' => 'Ja','Class:ComRequest/Attribute:facebook_library/Value:no' => 'Nee',
	'Class:ComRequest/Attribute:facebook_library/Value:no+' => 'Nee',
	'Class:ComRequest/Attribute:facebook_library/Value:yes' => 'Ja',
	'Class:ComRequest/Attribute:facebook_library/Value:yes+' => 'Ja','Class:ComRequest/Attribute:facebook_culture/Value:no' => 'Nee',
	'Class:ComRequest/Attribute:facebook_culture/Value:no+' => 'Nee',
	'Class:ComRequest/Attribute:facebook_culture/Value:yes' => 'Ja',
	'Class:ComRequest/Attribute:facebook_culture/Value:yes+' => 'Ja',
	'Class:ComRequest/Attribute:facebook_museum/Value:no' => 'Nee',
	'Class:ComRequest/Attribute:facebook_museum/Value:no+' => 'Nee',
	'Class:ComRequest/Attribute:facebook_museum/Value:yes' => 'Ja',
	'Class:ComRequest/Attribute:facebook_museum/Value:yes+' => 'Ja','Class:ComRequest/Attribute:facebook_youth/Value:no' => 'Nee',
	'Class:ComRequest/Attribute:facebook_youth/Value:no+' => 'Nee',
	'Class:ComRequest/Attribute:facebook_youth/Value:yes' => 'Ja',
	'Class:ComRequest/Attribute:facebook_youth/Value:yes+' => 'Ja','Class:ComRequest/Attribute:facebook_sport/Value:no' => 'Nee',
	'Class:ComRequest/Attribute:facebook_sport/Value:no+' => 'Nee',
	'Class:ComRequest/Attribute:facebook_sport/Value:yes' => 'Ja',
	'Class:ComRequest/Attribute:facebook_sport/Value:yes+' => 'Ja','Class:ComRequest/Attribute:facebook_market/Value:no' => 'Nee',
	'Class:ComRequest/Attribute:facebook_market/Value:no+' => 'Nee',
	'Class:ComRequest/Attribute:facebook_market/Value:yes' => 'Ja',
	'Class:ComRequest/Attribute:facebook_market/Value:yes+' => 'Ja','Class:ComRequest/Attribute:facebook_homemade/Value:no' => 'Nee',
	'Class:ComRequest/Attribute:facebook_homemade/Value:no+' => 'Nee',
	'Class:ComRequest/Attribute:facebook_homemade/Value:yes' => 'Ja',
	'Class:ComRequest/Attribute:facebook_homemade/Value:yes+' => 'Ja','Class:ComRequest/Attribute:instagram_museum/Value:no' => 'Nee',
	'Class:ComRequest/Attribute:instagram_museum/Value:no+' => 'Nee',
	'Class:ComRequest/Attribute:instagram_museum/Value:yes' => 'Ja',
	'Class:ComRequest/Attribute:instagram_museum/Value:yes+' => 'Ja','Class:ComRequest/Attribute:instagram_youth/Value:no' => 'Nee',
	'Class:ComRequest/Attribute:instagram_youth/Value:no+' => 'Nee',
	'Class:ComRequest/Attribute:instagram_youth/Value:yes' => 'Ja',
	'Class:ComRequest/Attribute:instagram_youth/Value:yes+' => 'Ja','Class:ComRequest/Attribute:magazine_youth/Value:no' => 'Nee',
	'Class:ComRequest/Attribute:magazine_youth/Value:no+' => 'Nee',
	'Class:ComRequest/Attribute:magazine_youth/Value:yes' => 'Ja',
	'Class:ComRequest/Attribute:magazine_youth/Value:yes+' => 'Ja','Class:ComRequest/Attribute:twitter_library/Value:no' => 'Nee',
	'Class:ComRequest/Attribute:twitter_library/Value:no+' => 'Nee',
	'Class:ComRequest/Attribute:twitter_library/Value:yes' => 'Ja',
	'Class:ComRequest/Attribute:twitter_library/Value:yes+' => 'Ja',
	'Class:ComRequest/Attribute:twitter_youth/Value:no' => 'Nee',
	'Class:ComRequest/Attribute:twitter_youth/Value:no+' => 'Nee',
	'Class:ComRequest/Attribute:twitter_youth/Value:yes' => 'Ja',
	'Class:ComRequest/Attribute:twitter_youth/Value:yes+' => 'Ja',
	
	'Class:ComRequest/Attribute:graphic_work_needed' => 'Grafisch werk nodig',
	'Class:ComRequest/Attribute:graphic_work_needed+' => 'Grafisch werk nodig',
	'Class:ComRequest/Attribute:graphic_work_needed/Value:needed' => 'Ja, nodig',
	'Class:ComRequest/Attribute:graphic_work_needed/Value:needed+' => 'Ja, nodig',
	'Class:ComRequest/Attribute:graphic_work_needed/Value:not_needed' => 'Niet nodig',
	'Class:ComRequest/Attribute:graphic_work_needed/Value:not_needed+' => 'Niet nodig',
	'Class:ComRequest/Attribute:graphic_work_needed/Value:done' => 'Afgewerkt',
	'Class:ComRequest/Attribute:graphic_work_needed/Value:done+' => 'Afgewerkt',
	'Class:ComRequest/Attribute:graphic_work_needed/Value:wip' => 'Lopende',
	'Class:ComRequest/Attribute:graphic_work_needed/Value:wip+' => 'Lopende',

	
	
	'Class:ComRequest/Method:ResolveChildTickets' => 'ResolveChildTickets',
	'Class:ComRequest/Method:ResolveChildTickets+' => 'Cascade the resolution to child requests (ev_autoresolve), and align the following characteristics of the request: service, team, agent, resolution info',
));
